import { expect, test } from '@playwright/test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Story 12.7 (AC2) — the first-run smoke: one headless pass that catches
// verify-gate, dead-handoff, and dead-UI regressions together.
//
//   anon → / → LANDING PAGE (story 6.1; no more redirect-to-login) → CTA → /register
//   register a fresh account → /library (empty first-run state)
//   + New song → NewSongDialog → UnifiedUploadDialog (mix only)
//   Upload & analyze → /songs/$songId/results/$jobId
//   wait for the report (ReportView), assert the job never fails
//   Open in Listen → /listen-rack/$versionId mounts
//
// Pre-reqs (the Playwright webServer only starts Vite — the rest must be up):
//   * docker compose -f docker/docker-compose.yml up -d postgres redis
//   * dotnet ef database update (migrations applied)
//   * BFF: ASPNETCORE_ENVIRONMENT=Development dotnet run (:5000) —
//     Development is REQUIRED: Auth:DevAutoVerify=true auto-verifies the
//     fresh account so the dispatch is not blocked by the verify gate.
//   * worker: python -m dramatiq app.dramatiq_app --processes 1 --threads 1
//     --queues coach analysis-paid analysis-free maintenance
//     from an interpreter with audio_analysis installed and LLM_FAKE=1
//     (components/worker/.env) — zero Anthropic spend, deterministic verdicts.
//   * MinIO NOT required: the presigned probe 501s and the mix upload takes
//     the legacy proxy fallback path (which this smoke then exercises).
//   * No allin1 docker image needed: structure detection degrades
//     gracefully and the job still completes (the fast path).
//   * test-tone.wav is generated by playwright/global-setup.ts if missing.
//
// HEADLESS ONLY — never pass --headed/--ui on shared/dev machines.

test.describe.configure({ mode: 'serial' });

test('first-run: register → upload → report → listen', async ({ page }) => {
  test.setTimeout(360_000); // cold worker + first-run model warmup budget

  // Diagnostics: API traffic + page errors land in the test output so a
  // failure at any step shows WHAT the app was doing (worker down, 4xx code,
  // console crash) without re-running under a tracer.
  // Query strings redacted: audio/SSE URLs carry short-lived JWTs (?t=) that
  // must not land in test logs / CI artifacts.
  const redact = (u: string) => u.split('?')[0];
  page.on('request', (r) => {
    if (r.url().includes('/api/')) console.log(`>> ${r.method()} ${redact(r.url())}`);
  });
  page.on('response', (r) => {
    if (r.url().includes('/api/')) console.log(`<< ${r.status()} ${redact(r.url())}`);
  });
  page.on('pageerror', (e) => console.log(`PAGE ERROR: ${e.message}`));

  // 1. Anon visit renders the landing page (story 6.1) with the primary CTA.
  await page.goto('/');
  await expect(page.getByTestId('landing-cta')).toBeVisible();
  await expect(page.getByTestId('landing-cta')).toHaveText(/Analyze my track free/);

  // 1b. The _app guard still bounces anon users off protected routes — the
  //     old anon /→/login assertion was this suite's only proof of the guard
  //     (review finding: keep it exercised now that / is public).
  await page.goto('/library');
  await expect(page).toHaveURL(/\/login(\?.*)?$/);
  await page.goto('/');

  // 2. CTA → register a fresh account (DevAutoVerify stamps it verified).
  await page.getByTestId('landing-cta').click();
  await expect(page).toHaveURL(/\/register$/);
  const emailBox = page.getByLabel('Email');
  const passwordBox = page.getByLabel('Password');
  // Cold Vite dev keeps streaming route modules after first paint; a late
  // module swap can REMOUNT the form and wipe a fill (controlled useState
  // resets), so the click submits empty fields and HTML5 `required` silently
  // blocks it. Settle the module graph, then fill→verify→submit→navigated as
  // ONE retried unit. Retry safety: a FRESH email is generated per attempt
  // (a slow-but-successful register can't dead-end on duplicate-email), and
  // an attempt that finds itself already past /register short-circuits.
  await page.waitForLoadState('networkidle');
  await expect(async () => {
    if (/\/library$/.test(new URL(page.url()).pathname)) return; // previous attempt landed
    const email = `smoke+${Date.now()}@spectr.test`;
    await emailBox.fill(email);
    await passwordBox.fill('correct-horse-battery-staple');
    await expect(emailBox).toHaveValue(email, { timeout: 500 });
    await page.getByRole('button', { name: /Create account/i }).click();
    // 3. Registration navigates to the library (full page nav).
    await expect(page).toHaveURL(/\/library$/, { timeout: 10_000 });
  }).toPass({ timeout: 90_000 });

  // 3b. Story 12.5 dead-UI guard: the unwired global search box and the
  //     permanently-disabled Listen nav tab are GONE from the shell — while
  //     the LIVE nav tabs remain (guards against over-deletion too).
  await expect(page.getByPlaceholder(/Search your tracks/)).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Listen', exact: true })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Report', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Library', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Feed', exact: true })).toBeVisible();

  // 3c. Story 12.8: a fresh library is no longer empty — the seeded demo
  //     report replaces the 'starts here' zero state as the first-run view.
  await expect(page.getByText('Demo: Sample Report')).toBeVisible();

  // 4. Two-dialog flow: + New song → name → Create song → upload dialog.
  await page.getByRole('button', { name: /\+ New song/ }).first().click();
  await page.getByPlaceholder('Untitled song').fill(`Smoke ${Date.now()}`);
  await page.getByRole('button', { name: /^Create song$/ }).click();

  // 5. UnifiedUploadDialog (with songId → titled "New version"): attach the
  //    fixture to the MIX input specifically — the dialog holds several
  //    hidden file inputs (.als / reference / stems).
  await expect(page.getByRole('heading', { name: 'New version' })).toBeVisible();
  const fixture = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)), 'fixtures', 'test-tone.wav');
  await page.getByTestId('mix-file-input').setInputFiles(fixture);
  const submit = page.getByRole('button', { name: /Upload & analyze/ });
  await expect(submit).toBeEnabled({ timeout: 15_000 }); // entitlements loaded
  await submit.click();

  // 6. Results page is reached immediately; the report appears when the
  //    worker completes. Fail FAST if the pipeline errors instead of
  //    burning the full timeout.
  await expect(page).toHaveURL(/\/songs\/.+\/results\/.+/, { timeout: 60_000 });
  const report = page.getByTestId('report-view');
  const failed = page.getByText('Analysis failed.');
  await expect(report.or(failed).first()).toBeVisible({ timeout: 300_000 });
  await expect(failed, 'analysis job failed — check worker logs').toBeHidden();
  await expect(report).toBeVisible();

  // 7. Listen reachability: the library card's Play button routes to the
  //    Listen rack for the latest version. (The report's own "Open in
  //    Listen" stays disabled until a fix is committed to the rack — the
  //    fix-carry-over handoff itself is story 12-4's integration test.)
  await page.goto('/library');
  await page.getByTitle('Play latest version').first().click();
  await expect(page).toHaveURL(/\/listen-rack\/[0-9a-f-]+/i, { timeout: 15_000 });
  await expect(page.getByTestId('listen-rack-page')).toBeVisible();
});
