import { expect, test } from '@playwright/test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Task G7 step 3 / G7b — the public instant-analysis funnel, end to end:
//
//   logged-out /analyze → drop test-tone.wav (zero forms) → a guest session
//   is minted and the SAME mix-upload path the signed-in "+ New song" flow
//   uses runs → /songs/$songId/results/$jobId as a guest (banner visible)
//   → full 7-phase report renders → the coach's once-per-conversation brief
//   ends with the exact server-authored closing line → "Create free account"
//   → /register?from=guest (the guest-conversion branch, "Save your
//   progress") → fill a throwaway example.test address → submit → the SAME
//   account (same user id) lands on /library with the uploaded song listed
//   and the guest banner gone.
//
// Pre-reqs: same running stack as smoke-first-run (postgres+redis, BFF in
// Development with DevAutoVerify, worker with LLM_FAKE=1 for a free,
// deterministic coach brief). test-tone.wav is generated by
// playwright/global-setup.ts if missing.
//
// HEADLESS ONLY — never pass --headed/--ui on shared/dev machines.

test.describe.configure({ mode: 'serial' });

test('a logged-out visitor uploads a track, gets a guest report + coach brief, and converts in place', async ({
  page,
}) => {
  test.setTimeout(420_000); // up to 6 min of analysis + register/library steps

  // Diagnostics: API traffic + page errors land in the test output. Query
  // strings redacted: audio/SSE URLs carry short-lived JWTs (?t=) that must
  // not land in test logs / CI artifacts.
  const redact = (u: string) => u.split('?')[0];
  page.on('request', (r) => {
    if (r.url().includes('/api/')) console.log(`>> ${r.method()} ${redact(r.url())}`);
  });
  page.on('response', (r) => {
    if (r.url().includes('/api/')) console.log(`<< ${r.status()} ${redact(r.url())}`);
  });
  page.on('pageerror', (e) => console.log(`PAGE ERROR: ${e.message}`));

  // 1. The public funnel page: full-bleed drop zone, zero form fields.
  await page.goto('/analyze');
  await expect(page.getByTestId('anon-drop-zone')).toBeVisible();
  await expect(page.getByText('WAV · FLAC · MP3 · ≤250 MB · no forms, ever')).toBeVisible();

  // 2. Drop the fixture via the hidden file input (drag-drop is the same
  //    code path through onFile).
  const fixture = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    'fixtures',
    'test-tone.wav',
  );
  await page.getByTestId('anon-file-input').setInputFiles(fixture);

  // 3. A guest session is minted (or resumed) and the mix upload runs, then
  //    the SAME signed-in results route the authed flow uses is reached.
  await expect(page).toHaveURL(/\/songs\/.+\/results\/.+/, { timeout: 60_000 });
  await expect(page.getByText(/as a guest/i)).toBeVisible();

  const songId = new URL(page.url()).pathname.match(/\/songs\/([^/]+)\//)?.[1];
  expect(songId, 'could not parse songId out of the results URL').toBeTruthy();

  // A guest's own upload also gets the "Analysis complete" dialog (only the
  // demo song suppresses it — analysis-complete-gate.ts), and it opens at a
  // moment the page decides. A visitor closes it before acting on the brief,
  // so the smoke closes it whenever it appears. (The handler keys on the
  // dialog's Close button: the dialog root itself has no box of its own, so
  // Playwright never reports the root as visible.)
  const closeCompleteDialog = page
    .getByRole('dialog', { name: 'Analysis' })
    .getByRole('button', { name: 'Close' });
  await page.addLocatorHandler(closeCompleteDialog, async (close) => {
    await close.click();
  });

  // 4. The report renders once the pipeline completes. Fail fast if the job
  //    errors instead of burning the full timeout.
  const report = page.getByTestId('report-view');
  const failed = page.getByText('Analysis failed.');
  await expect(report.or(failed).first()).toBeVisible({ timeout: 300_000 });
  await expect(failed, 'analysis job failed — check worker logs').toBeHidden();
  await expect(report).toBeVisible();

  // 5. The coach's opening brief fires once triage is done (useCoachBrief)
  //    and, for a guest, ends with the server's exact closing line
  //    (CoachBrief.GuestClosingLine, CoachConversationDtos.cs). Never
  //    weakened to a substring/regex match — this sentence is the product's
  //    conversion moment.
  const closingLine =
    "Create a free account and let's save our progress — so we can make this mix awesome.";
  await expect(page.getByText(closingLine, { exact: true })).toBeVisible({ timeout: 150_000 });

  // 6. Click through to registration on the guest-conversion branch.
  await page.getByRole('link', { name: 'Create free account', exact: true }).click();
  await expect(page).toHaveURL(/\/register\?from=guest/, { timeout: 15_000 });
  await expect(page.getByRole('heading', { name: 'Save your progress' })).toBeVisible();

  // 7. Fill a unique throwaway address on the reserved test domain and
  //    submit. Conversion keeps the SAME user id in place (GuestConvertEndpoints.cs).
  const email = `guest-smoke-${Date.now()}@example.test`;
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill('smoke-Passw0rd!');
  await page.getByRole('button', { name: 'Create account' }).click();

  // 8. Dev auto-verify issues a session directly (no separate /login hop) —
  //    the browser lands on /library as the now-real account.
  await expect(page).toHaveURL(/\/library$/, { timeout: 30_000 });
  await expect(page.getByText(/as a guest/i)).toHaveCount(0);

  // 9. Same account, converted in place: the uploaded song is still there.
  await expect(page.locator(`a[href^="/songs/${songId}"]`).first()).toBeVisible({
    timeout: 20_000,
  });
});
