/* GENERATED by scripts/gen-sample-report.mjs — do not edit by hand.
 * Source: demo snapshot (spectr-demo-snapshot/v1, exported 2026-09-21T16:27:46.2664704+00:00),
 * "Magnetic Fields" by Artifact303, used with permission. Real pipeline
 * output: 27 of 30 verdicts kept, clustered into 21 findings.
 * Excluded (contradicted in the same report):
 *   - rule_engine.weak_transients: Weak transient attack (0.76) — provisional threshold, contradicted by the Dynamics specialist measuring punchy transients
 *   - rule_engine.bpm_genre_match: BPM 185 outside modern_trance range — tempo read double-time on the short excerpt; the rule itself says it is likely a detection artefact
 *   - stereo_field: Very narrow stereo image — width score 8.6/100 — widening advice contradicted by the higher-priority Stereo Phase mono-collapse finding
 * Regenerate: node scripts/gen-sample-report.mjs <snapshot.json> */
import type { VerdictDto } from '../../../api/types';

export interface SampleCorroboration {
  specialist: string;
  headline: string;
}

export interface SampleFinding {
  verdict: VerdictDto;
  /** Other specialists that independently flagged the same measurement. */
  corroboratedBy: SampleCorroboration[];
}

export interface SampleMeta {
  title: string;
  artist: string;
  genre: string | null;
  key: string | null;
  grade: string;
  score: number;
  lufs: number | null;
  truePeakDb: number | null;
  crestFactorDb: number | null;
  loudnessRangeLu: number | null;
  stereoCorrelation: number | null;
  specialistsRun: string[];
  pipelineVersion: string;
  verdictsInSnapshot: number;
}

export const SAMPLE_META: SampleMeta = {
  "title": "Magnetic Fields",
  "artist": "Artifact303",
  "genre": "classic_trance",
  "key": "D major",
  "grade": "F",
  "score": 43,
  "lufs": -16.9,
  "truePeakDb": -3.3,
  "crestFactorDb": 18.6,
  "loudnessRangeLu": 7.2,
  "stereoCorrelation": 0.12,
  "specialistsRun": [
    "stereo_phase",
    "stereo_field",
    "low_end",
    "frequency_balance",
    "dynamics",
    "loudness"
  ],
  "pipelineVersion": "2.2.0",
  "verdictsInSnapshot": 30
};

export const SAMPLE_FINDINGS: SampleFinding[] = [
  {
    "verdict": {
      "id": "sample-17",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "loudness",
      "confidence": 0.74,
      "priorityScore": 98,
      "impact": "med",
      "chartType": null,
      "headline": "Integrated loudness -16.9 LUFS: 2.9 dB under the -14 streaming target",
      "summary": "Integrated loudness is -16.9 LUFS: 2.9 dB under the -14 LUFS Spotify/YouTube/Tidal target, 0.9 dB under Apple's -16, and 7.9 dB under a -9 club master. The clip is 9.2 s with a 2.5 s fade-in, and its body sits around -16 to -17 LUFS. True peak is -3.3 dBTP, so +2.9 dB needs only ~0.6 dB of limiting.",
      "body": "Integrated loudness is -16.9 LUFS: 2.9 dB under the -14 LUFS Spotify/YouTube/Tidal target, 0.9 dB under Apple's -16, and 7.9 dB under a -9 club master. The clip is 9.2 s with a 2.5 s fade-in, and its body sits around -16 to -17 LUFS. True peak is -3.3 dBTP, so +2.9 dB needs only ~0.6 dB of limiting.",
      "metricLine": "Integrated LUFS, 2.9 dB under -14",
      "whyItMatters": "Spotify barely boosts quiet tracks, so at -16.9 LUFS this plays audibly softer and weaker than -14 LUFS masters beside it in a playlist.",
      "presetName": null,
      "evidence": [
        {
          "label": "Integrated LUFS, 2.9 dB under -14",
          "stems": null,
          "value": -16.885,
          "metric": "phase1.lufs",
          "delta_pct": null,
          "expected_range": [
            -14.5,
            -13.5
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Loudest 3 s window still under -14",
          "stems": null,
          "value": -15.785,
          "metric": "phase1.short_term_max_lufs",
          "delta_pct": null,
          "expected_range": [
            -13,
            -10
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Loudest moment peaks at -13.0 LUFS",
          "stems": null,
          "value": -13.04,
          "metric": "phase1.momentary_max_lufs",
          "delta_pct": null,
          "expected_range": [
            -11,
            -8
          ],
          "frequency_range_hz": null
        },
        {
          "label": "2.3 dB of true-peak headroom unused",
          "stems": null,
          "value": -3.329,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -6,
            -1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Short clip: integrated reading less stable",
          "stems": null,
          "value": 9.221,
          "metric": "phase1.duration_seconds",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "gain",
            "params": {
              "gain_db": 2.9
            }
          },
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1,
              "release_ms": 80,
              "lookahead_ms": 1.5,
              "threshold_db": -1
            }
          }
        ],
        "expected_outcome": "The track plays at about -14 LUFS with peaks held at -1.0 dBTP, so it matches neighbouring tracks on Spotify and YouTube; only ~0.6 dB of limiting is needed, so transients stay intact.",
        "ableton_hint": {
          "band": 0,
          "device": "Limiter",
          "preset_name": "Streaming -14 LUFS, -1 dB ceiling"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-04",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "mono_compatibility",
      "confidence": 0.72,
      "priorityScore": 98,
      "impact": "med",
      "chartType": null,
      "headline": "Correlation 0.12: mix is on the edge of collapsing in mono",
      "summary": "L/R correlation is 0.118, under the 0.15 collapse line and well below the 0.3-0.7 target. The mono fold keeps 74% of RMS (about -2.6 dB), barely clearing the 0.7 pass mark. Correlation is positive: decorrelation, not inverted polarity. Only 9 s analysed.",
      "body": "L/R correlation is 0.118, under the 0.15 collapse line and well below the 0.3-0.7 target. The mono fold keeps 74% of RMS (about -2.6 dB), barely clearing the 0.7 pass mark. Correlation is positive: decorrelation, not inverted polarity. Only 9 s analysed.",
      "metricLine": "L/R correlation, near-unrelated channels",
      "whyItMatters": "Club subs, phones and Bluetooth speakers sum to mono; decorrelated content drops in level and thins out there, and any further widening tips this into real cancellation.",
      "presetName": null,
      "evidence": [
        {
          "label": "L/R correlation, near-unrelated channels",
          "stems": null,
          "value": 0.11774036910481339,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0.3,
            0.7
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Mono fold RMS ratio, barely passing",
          "stems": null,
          "value": 0.7435073037275717,
          "metric": "phase1.mono_compatibility",
          "delta_pct": null,
          "expected_range": [
            0.7,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Spatial mono compatibility score",
          "stems": null,
          "value": 55.64432954250237,
          "metric": "phase9.surround.mono_compatibility",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Phase score, some cancellation present",
          "stems": null,
          "value": 55.88701845524067,
          "metric": "phase9.surround.phase_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "stereo_width",
            "params": {
              "width_pct": 80
            }
          }
        ],
        "expected_outcome": "The mix keeps its level and body when summed to mono, with correlation rising toward 0.3 while still sounding wide in stereo.",
        "ableton_hint": {
          "band": 0,
          "device": "Utility",
          "preset_name": "Width 80% + Bass Mono 120 Hz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-09",
      "analysisId": "sample",
      "specialist": "low_end",
      "promptVersion": "low_end@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "low_end",
      "confidence": 0.62,
      "priorityScore": 91,
      "impact": "med",
      "chartType": null,
      "headline": "Low-mid mud: 250–500 Hz only 2 dB under the bass band",
      "summary": "Low-mids sit at -34.8 dBFS against bass at -32.8, a 2.1 dB gap where 4–6 dB is the target. Phase 4 also flags high-severity congestion at 200–500 Hz. A broad cut of about 2.5 dB at 300 Hz restores the separation.",
      "body": "Low-mids sit at -34.8 dBFS against bass at -32.8, a 2.1 dB gap where 4–6 dB is the target. Phase 4 also flags high-severity congestion at 200–500 Hz. A broad cut of about 2.5 dB at 300 Hz restores the separation.",
      "metricLine": "Low-mid level; target is 4–6 dB under bass",
      "whyItMatters": "Bass harmonics, kick body and pads all stack up at 200–400 Hz. Excess energy there masks the fundamentals and makes the low end sound boomy and undefined.",
      "presetName": null,
      "evidence": [
        {
          "label": "Low-mid level; target is 4–6 dB under bass",
          "stems": null,
          "value": -34.84,
          "metric": "phase1.bands.low_mid",
          "delta_pct": null,
          "expected_range": [
            -38.8,
            -36.8
          ],
          "frequency_range_hz": [
            250,
            500
          ]
        },
        {
          "label": "Bass band level, used as the comparison point",
          "stems": null,
          "value": -32.77,
          "metric": "phase1.bands.bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Low-mid congestion flagged 'high'",
          "stems": null,
          "value": null,
          "metric": "phase4.clashes[1].severity",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            200,
            500
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -2.5,
              "frequency_hz": 300
            }
          }
        ],
        "expected_outcome": "The low end sounds tighter and less boxy, with a clearer gap between bass weight and the midrange.",
        "ableton_hint": {
          "band": 3,
          "device": "EQ Eight",
          "preset_name": "Mud cut 300 Hz -2.5 dB"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "frequency_balance",
        "headline": "Low-mid sits level with the mid band — mud is masking the body"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-10",
      "analysisId": "sample",
      "specialist": "low_end",
      "promptVersion": "low_end@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "low_end",
      "confidence": 0.55,
      "priorityScore": 91,
      "impact": "med",
      "chartType": null,
      "headline": "Low-end buildup at 20–200 Hz, with sub-30 Hz content present",
      "summary": "Phase 4 flags high-severity buildup across 20–200 Hz. Bass is the hottest band, at 22.7 against a mid band of 16.4. Sub-30 Hz energy reads 0.61, so inaudible rumble is likely using headroom. High-pass at 30 Hz and trim 1.5 dB around 120 Hz.",
      "body": "Phase 4 flags high-severity buildup across 20–200 Hz. Bass is the hottest band, at 22.7 against a mid band of 16.4. Sub-30 Hz energy reads 0.61, so inaudible rumble is likely using headroom. High-pass at 30 Hz and trim 1.5 dB around 120 Hz.",
      "metricLine": "Low-end buildup flagged 'high'",
      "whyItMatters": "Rumble below 30 Hz is inaudible but still drives the limiter. At -16.9 LUFS, removing it gives cheap headroom for a louder, cleaner master.",
      "presetName": null,
      "evidence": [
        {
          "label": "Low-end buildup flagged 'high'",
          "stems": null,
          "value": null,
          "metric": "phase4.clashes[0].severity",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            20,
            200
          ]
        },
        {
          "label": "Bass is the dominant band, 6.3 dB over mid",
          "stems": null,
          "value": 22.72,
          "metric": "phase4.band_energy.bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Energy below 30 Hz, which is felt by no one",
          "stems": null,
          "value": 0.6054,
          "metric": "phase1.sub_30_energy",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            20,
            30
          ]
        },
        {
          "label": "Sub-bass sits 4.7 dB under bass, a fair ratio",
          "stems": null,
          "value": -37.44,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            20,
            60
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.71,
              "slope_db": 24,
              "frequency_hz": 30
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -1.5,
              "frequency_hz": 120
            }
          }
        ],
        "expected_outcome": "The low end keeps the same weight but sounds cleaner, and the freed headroom lets the master come up toward target loudness.",
        "ableton_hint": {
          "band": 1,
          "device": "EQ Eight",
          "preset_name": "HP 30 Hz 24 dB + 120 Hz trim"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-24",
      "analysisId": "sample",
      "specialist": "stereo_field",
      "promptVersion": "stereo_field@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "stereo_field",
      "confidence": 0.8,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Mix leans 4.1 dB to the left — stereo image is lopsided",
      "summary": "Left channel RMS is -20.3 dB and right is -24.5 dB, a 4.1 dB tilt. A balanced mix sits within ±1 dB. Something loud is panned left with no counterweight. Check kick, bass, snare and lead are at pan 0, then mirror each left-panned part with a similar part on the right.",
      "body": "Left channel RMS is -20.3 dB and right is -24.5 dB, a 4.1 dB tilt. A balanced mix sits within ±1 dB. Something loud is panned left with no counterweight. Check kick, bass, snare and lead are at pan 0, then mirror each left-panned part with a similar part on the right.",
      "metricLine": "L minus R RMS balance (dB)",
      "whyItMatters": "A 4 dB tilt makes the whole track feel off-center on headphones and drops level on one side of a club or car system.",
      "presetName": null,
      "evidence": [
        {
          "label": "L minus R RMS balance (dB)",
          "stems": null,
          "value": 4.125,
          "metric": "phase1.channel_balance.balance_db",
          "delta_pct": null,
          "expected_range": [
            -1,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Left channel RMS",
          "stems": null,
          "value": -20.35,
          "metric": "phase1.channel_balance.l_rms_db",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Right channel RMS",
          "stems": null,
          "value": -24.47,
          "metric": "phase1.channel_balance.r_rms_db",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "gain",
            "params": {
              "gain_db": -2
            }
          }
        ],
        "expected_outcome": "With the left side trimmed about 2 dB and the right raised to match, the phantom center locks in the middle instead of pulling toward the left speaker.",
        "ableton_hint": {
          "band": 0,
          "device": "Utility",
          "preset_name": "Balance ~20R as stopgap; re-pan sources"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "rule_engine.channel_imbalance",
        "headline": "Channel imbalance — left louder by 4.1 dB"
      },
      {
        "specialist": "stereo_phase",
        "headline": "Image leans left: L channel 4.1 dB hotter than R"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-13",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.8,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Air and presence bands are effectively absent — mix is dark",
      "summary": "Air (-79.4 dB) is 44 dB below mid and presence (-66.0 dB) is 31 dB below, so the top end is effectively missing. The source is an MP3, so an encoder or synth low-pass is likely. A shelf can't restore missing content. Remove low-pass filters, re-export lossless, then add the shelf.",
      "body": "Air (-79.4 dB) is 44 dB below mid and presence (-66.0 dB) is 31 dB below, so the top end is effectively missing. The source is an MP3, so an encoder or synth low-pass is likely. A shelf can't restore missing content. Remove low-pass filters, re-export lossless, then add the shelf.",
      "metricLine": "Air level (dark if >12 dB under mid)",
      "whyItMatters": "With no energy above 6 kHz the mix sounds dull and distant on any system. Sparkle and vertical space cannot be added at mastering.",
      "presetName": null,
      "evidence": [
        {
          "label": "Air level (dark if >12 dB under mid)",
          "stems": null,
          "value": -79.44,
          "metric": "phase1.bands.air",
          "delta_pct": null,
          "expected_range": [
            -47.2,
            -41
          ],
          "frequency_range_hz": [
            6000,
            20000
          ]
        },
        {
          "label": "Presence band 31 dB under mid",
          "stems": null,
          "value": -65.98,
          "metric": "phase1.bands.presence",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            4000,
            8000
          ]
        },
        {
          "label": "Low height perception (lacks presence/air)",
          "stems": null,
          "value": 13.52,
          "metric": "phase9.spatial.height_score",
          "delta_pct": null,
          "expected_range": [
            40,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_shelf",
            "params": {
              "q": 0.7,
              "gain_db": 3,
              "frequency_hz": 10000
            }
          }
        ],
        "expected_outcome": "Once the low-pass cause is removed, the shelf adds audible shimmer and openness so hats and synth tops stop sounding veiled.",
        "ableton_hint": {
          "band": 8,
          "device": "EQ Eight",
          "preset_name": "Air shelf +3 dB 10k"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "rule_engine.dull_no_air",
        "headline": "Dull top end - missing air"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-14",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "clarity",
      "confidence": 0.68,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Upper-mid sits 13 dB under mid — attack and definition are weak",
      "summary": "Upper-mid (-48.4 dB) is 13.2 dB below mid. It should sit only a few dB under. Attack and definition at 2-6 kHz are weak. Add a broad +2.5 dB at 3.5 kHz on the master. Caveat: the clip is 9 s with a ~2.5 s fade-in, which skews whole-file band averages.",
      "body": "Upper-mid (-48.4 dB) is 13.2 dB below mid. It should sit only a few dB under. Attack and definition at 2-6 kHz are weak. Add a broad +2.5 dB at 3.5 kHz on the master. Caveat: the clip is 9 s with a ~2.5 s fade-in, which skews whole-file band averages.",
      "metricLine": "Upper-mid level (target slightly under mid)",
      "whyItMatters": "2-6 kHz carries attack and intelligibility. When it is this far under the mids, the mix sounds soft and blurred even at volume.",
      "presetName": null,
      "evidence": [
        {
          "label": "Upper-mid level (target slightly under mid)",
          "stems": null,
          "value": -48.39,
          "metric": "phase1.bands.upper_mid",
          "delta_pct": null,
          "expected_range": [
            -40,
            -36
          ],
          "frequency_range_hz": [
            2000,
            6000
          ]
        },
        {
          "label": "Mid band level (comparison anchor)",
          "stems": null,
          "value": -35.16,
          "metric": "phase1.bands.mid",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            500,
            2000
          ]
        },
        {
          "label": "Very short clip — averages less reliable",
          "stems": null,
          "value": 9.22,
          "metric": "phase1.duration_seconds",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 0.8,
              "gain_db": 2.5,
              "frequency_hz": 3500
            }
          }
        ],
        "expected_outcome": "Transients and lead edges cut through with more definition without the mix turning harsh.",
        "ableton_hint": {
          "band": 6,
          "device": "EQ Eight",
          "preset_name": "Broad clarity lift 3.5k"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-20",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "dynamics",
      "confidence": 0.6,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Crest factor 18.6 dB — mix is too dynamic, under-glued",
      "summary": "Crest factor is 18.6 dB (peak -3.3 dBFS vs RMS -21.9 dBFS). That is above the 8-12 dB target and past the 16 dB 'too dynamic' line. Caveat: the clip is only 9.2 s and fades in over ~3 s, which inflates the figure, so the sustained part is likely less extreme.",
      "body": "Crest factor is 18.6 dB (peak -3.3 dBFS vs RMS -21.9 dBFS). That is above the 8-12 dB target and past the 16 dB 'too dynamic' line. Caveat: the clip is only 9.2 s and fades in over ~3 s, which inflates the figure, so the sustained part is likely less extreme.",
      "metricLine": "Crest factor dB (very dynamic band)",
      "whyItMatters": "At 18+ dB crest the body of the mix sits far below its peaks, so it sounds small and quiet next to finished tracks even though the hits are strong.",
      "presetName": null,
      "evidence": [
        {
          "label": "Crest factor dB (very dynamic band)",
          "stems": null,
          "value": 18.5964601730317,
          "metric": "phase1.crest_factor",
          "delta_pct": null,
          "expected_range": [
            8,
            12
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Linear RMS = -21.9 dBFS",
          "stems": null,
          "value": 0.07999289035797119,
          "metric": "phase1.rms",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Loudness range LU (fade-in included)",
          "stems": null,
          "value": 7.248837674470195,
          "metric": "phase1.loudness_range_lu",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Short clip — crest figure is inflated",
          "stems": null,
          "value": 9.221224489795919,
          "metric": "phase1.duration_seconds",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "compressor",
            "params": {
              "ratio": 2,
              "knee_db": 6,
              "attack_ms": 30,
              "release_ms": 100,
              "threshold_db": -10,
              "makeup_gain_db": 1.5
            }
          },
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1,
              "release_ms": 50,
              "lookahead_ms": 3,
              "threshold_db": -5
            }
          }
        ],
        "expected_outcome": "The mix sounds tighter and denser with crest factor near 11-13 dB, and the 30 ms attack keeps the existing punch intact.",
        "ableton_hint": {
          "band": 0,
          "device": "Glue Compressor",
          "preset_name": "Master glue 2:1 slow attack"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-25",
      "analysisId": "sample",
      "specialist": "stereo_field",
      "promptVersion": "stereo_field@1.0.0",
      "model": "claude-cli",
      "severity": "moderate",
      "category": "stereo_field",
      "confidence": 0.55,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Stereo width drifts — consistency only 23%",
      "summary": "Width consistency is 23%, so the image swings between narrow and wide with no clear intent. Give core elements fixed pan positions. Keep width movement for deliberate automation, such as opening pads and FX from ±40 to ±80 into a drop, rather than leaving it to modulating wideners or auto-pan.",
      "body": "Width consistency is 23%, so the image swings between narrow and wide with no clear intent. Give core elements fixed pan positions. Keep width movement for deliberate automation, such as opening pads and FX from ±40 to ±80 into a drop, rather than leaving it to modulating wideners or auto-pan.",
      "metricLine": "Width consistency score",
      "whyItMatters": "Random width drift makes the image feel unstable. Deliberate width changes make section transitions feel bigger.",
      "presetName": null,
      "evidence": [
        {
          "label": "Width consistency score",
          "stems": null,
          "value": 23.02,
          "metric": "phase9.spatial.width_consistency",
          "delta_pct": null,
          "expected_range": [
            60,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "rule_engine.width_instability",
        "headline": "Stereo width wanders (23/100)"
      },
      {
        "specialist": "stereo_phase",
        "headline": "Stereo width drifts: consistency only 23/100"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-15",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-cli",
      "severity": "minor",
      "category": "low_end",
      "confidence": 0.5,
      "priorityScore": 39,
      "impact": "med",
      "chartType": null,
      "headline": "60-250 Hz buildup flagged — low end slightly heavy against the mids",
      "summary": "The spectral pass puts bass 6.3 dB above mid and flags 20-200 Hz buildup. The whole-file bands show only +2.4 dB, which is inside the normal bass≈mid hierarchy, so the two readings disagree. Treat this as a light trim, not a rebuild: a gentle wide cut around 120 Hz after the mud cut.",
      "body": "The spectral pass puts bass 6.3 dB above mid and flags 20-200 Hz buildup. The whole-file bands show only +2.4 dB, which is inside the normal bass≈mid hierarchy, so the two readings disagree. Treat this as a light trim, not a rebuild: a gentle wide cut around 120 Hz after the mud cut.",
      "metricLine": "Spectral pass: bass 6.3 dB over mid",
      "whyItMatters": "Excess 60-250 Hz energy eats headroom and masks the mids, but over-cutting would thin a foundation that currently measures healthy.",
      "presetName": null,
      "evidence": [
        {
          "label": "Spectral pass: bass 6.3 dB over mid",
          "stems": null,
          "value": 22.72,
          "metric": "phase4.band_energy.bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Spectral pass: mid reference",
          "stems": null,
          "value": 16.41,
          "metric": "phase4.band_energy.mid",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            500,
            2000
          ]
        },
        {
          "label": "Whole-file bass: only 2.4 dB over mid",
          "stems": null,
          "value": -32.77,
          "metric": "phase1.bands.bass",
          "delta_pct": null,
          "expected_range": [
            -38.2,
            -29.2
          ],
          "frequency_range_hz": [
            60,
            250
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 0.8,
              "gain_db": -1.5,
              "frequency_hz": 120
            }
          }
        ],
        "expected_outcome": "The low end tightens slightly and leaves more room for the mids without losing weight.",
        "ableton_hint": {
          "band": 2,
          "device": "EQ Eight",
          "preset_name": "Gentle bass trim 120 Hz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-26",
      "analysisId": "sample",
      "specialist": "stereo_field",
      "promptVersion": "stereo_field@1.0.0",
      "model": "claude-cli",
      "severity": "minor",
      "category": "stereo_field",
      "confidence": 0.9,
      "priorityScore": 30,
      "impact": "med",
      "chartType": null,
      "headline": "No per-track pan data — pan plan is by element type only",
      "summary": "Only a 9.2 s stereo mixdown was analyzed. No Ableton project was supplied, so current pan values could not be read and the pan plan above is a generic starting point by element type, not a per-track plan. Upload the .als for track-by-track pan recommendations and a left/right balance check.",
      "body": "Only a 9.2 s stereo mixdown was analyzed. No Ableton project was supplied, so current pan values could not be read and the pan plan above is a generic starting point by element type, not a per-track plan. Upload the .als for track-by-track pan recommendations and a left/right balance check.",
      "metricLine": "Analyzed clip length (s)",
      "whyItMatters": "Mix-level meters show that the image is lopsided and narrow, but not which tracks are causing it.",
      "presetName": null,
      "evidence": [
        {
          "label": "Analyzed clip length (s)",
          "stems": null,
          "value": 9.22,
          "metric": "phase1.duration_seconds",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-21",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-cli",
      "severity": "minor",
      "category": "gain_staging",
      "confidence": 0.8,
      "priorityScore": 30,
      "impact": "med",
      "chartType": null,
      "headline": "Peak at -3.3 dBFS — 2.3 dB of headroom unused",
      "summary": "Peak level is -3.34 dBFS (true peak -3.33 dBTP), just under the -3 to -1 dBFS target window. Combined with an RMS of -21.9 dBFS, the master is quiet. About 2.3 dB of clean gain is available before any limiting is needed.",
      "body": "Peak level is -3.34 dBFS (true peak -3.33 dBTP), just under the -3 to -1 dBFS target window. Combined with an RMS of -21.9 dBFS, the master is quiet. About 2.3 dB of clean gain is available before any limiting is needed.",
      "metricLine": "Sample peak dBFS",
      "whyItMatters": "Unused headroom is free loudness, and using it first means less limiting is needed later to reach a competitive level.",
      "presetName": null,
      "evidence": [
        {
          "label": "Sample peak dBFS",
          "stems": null,
          "value": -3.3425119324239945,
          "metric": "phase1.peak_dbfs",
          "delta_pct": null,
          "expected_range": [
            -3,
            -1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "True peak dBTP",
          "stems": null,
          "value": -3.3294694407531065,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -3,
            -1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "gain",
            "params": {
              "gain_db": 2.3
            }
          }
        ],
        "expected_outcome": "The track plays about 2 dB louder with no change in tone or dynamics; skip this if you apply the glue-plus-limiter chain, which already takes up the headroom.",
        "ableton_hint": {
          "band": 0,
          "device": "Utility",
          "preset_name": "Gain +2.3 dB"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-07",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-cli",
      "severity": "minor",
      "category": "stereo_phase",
      "confidence": 0.55,
      "priorityScore": 30,
      "impact": "med",
      "chartType": null,
      "headline": "Width metric reads narrow; do not respond by adding wideners",
      "summary": "Stereo width reads 0.107 (narrow) while correlation reads very wide at 0.118. The two disagree, so treat correlation and the mono fold as the authority. Adding wideners to chase the width number would push mono compatibility under the 0.7 release line.",
      "body": "Stereo width reads 0.107 (narrow) while correlation reads very wide at 0.118. The two disagree, so treat correlation and the mono fold as the authority. Adding wideners to chase the width number would push mono compatibility under the 0.7 release line.",
      "metricLine": "Stereo width reading",
      "whyItMatters": "Chasing a low width score with stereo enhancers is the fastest way to turn a borderline mono fold into audible cancellation.",
      "presetName": null,
      "evidence": [
        {
          "label": "Stereo width reading",
          "stems": null,
          "value": 0.10698698461055756,
          "metric": "phase1.stereo_width",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Stereo width sub-score",
          "stems": null,
          "value": 8.558958768844604,
          "metric": "phase3.sub_scores.stereo_width",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-23",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "clipping",
      "confidence": 0.95,
      "priorityScore": 30,
      "impact": "med",
      "chartType": null,
      "headline": "No clipping — 0 clipped samples",
      "summary": "clipping_detected is false with 0 clipped samples, and true peak sits at -3.33 dBTP. Nothing is being pushed into distortion. There is comfortable room to add glue compression and limiting without overs.",
      "body": "clipping_detected is false with 0 clipped samples, and true peak sits at -3.33 dBTP. Nothing is being pushed into distortion. There is comfortable room to add glue compression and limiting without overs.",
      "metricLine": "Clipping detected = false",
      "whyItMatters": "A clean, unclipped master means loudness can be raised deliberately without first having to repair distortion.",
      "presetName": null,
      "evidence": [
        {
          "label": "Clipping detected = false",
          "stems": null,
          "value": null,
          "metric": "phase1.clipping_detected",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Clipped samples",
          "stems": null,
          "value": 0,
          "metric": "phase1.clipped_sample_count",
          "delta_pct": null,
          "expected_range": [
            0,
            0
          ],
          "frequency_range_hz": null
        },
        {
          "label": "True peak dBTP — safe margin",
          "stems": null,
          "value": -3.3294694407531065,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1.5,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-18",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "clipping",
      "confidence": 0.92,
      "priorityScore": 30,
      "impact": "med",
      "chartType": null,
      "headline": "True peak -3.3 dBTP with zero clipped samples",
      "summary": "True peak is -3.33 dBTP, 2.33 dB inside the -1.0 dBTP streaming limit. No clipping was detected (0 clipped samples). The master passes streaming peak limits, with a small inter-sample margin for lossy encoding. The job is to use this headroom, not to fix overs.",
      "body": "True peak is -3.33 dBTP, 2.33 dB inside the -1.0 dBTP streaming limit. No clipping was detected (0 clipped samples). The master passes streaming peak limits, with a small inter-sample margin for lossy encoding. The job is to use this headroom, not to fix overs.",
      "metricLine": "True peak well under -1.0 dBTP",
      "whyItMatters": "True-peak overs are the top cause of streaming distortion and upload rejection. This master has none, so loudness can be raised safely.",
      "presetName": null,
      "evidence": [
        {
          "label": "True peak well under -1.0 dBTP",
          "stems": null,
          "value": -3.329,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -6,
            -1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "No clipped samples",
          "stems": null,
          "value": 0,
          "metric": "phase1.clipped_sample_count",
          "delta_pct": null,
          "expected_range": [
            0,
            0
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1.5,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-19",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "loudness",
      "confidence": 0.65,
      "priorityScore": 28,
      "impact": "med",
      "chartType": null,
      "headline": "Loudness range 7.2 LU is well controlled",
      "summary": "Loudness range is 7.2 LU, under the 12 LU 'too wide' threshold, so level rides are controlled and normalization won't leave sections buried. About 1.1 dB separates integrated LUFS from the loudest 3 s window. Part of the range in this 9 s clip comes from the fade-in.",
      "body": "Loudness range is 7.2 LU, under the 12 LU 'too wide' threshold, so level rides are controlled and normalization won't leave sections buried. About 1.1 dB separates integrated LUFS from the loudest 3 s window. Part of the range in this 9 s clip comes from the fade-in.",
      "metricLine": "LRA inside healthy window",
      "whyItMatters": "A controlled loudness range means one static gain change fixes the level; no section-by-section automation is needed to reach target.",
      "presetName": null,
      "evidence": [
        {
          "label": "LRA inside healthy window",
          "stems": null,
          "value": 7.249,
          "metric": "phase1.loudness_range_lu",
          "delta_pct": null,
          "expected_range": [
            4,
            12
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Short-term max 1.1 dB above integrated",
          "stems": null,
          "value": -15.785,
          "metric": "phase1.short_term_max_lufs",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-11",
      "analysisId": "sample",
      "specialist": "low_end",
      "promptVersion": "low_end@1.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "low_end",
      "confidence": 0.6,
      "priorityScore": 26,
      "impact": "med",
      "chartType": null,
      "headline": "Punch and bass translation are intact",
      "summary": "Average transient strength is 0.76 and crest factor is 18.6 dB, so attacks are not crushed. Speaker translation scores 80 and bass translation reads 'good'. There is no clipping, and true peak is -3.3 dBTP. The clip is only 9.2 s with a fade-in, so re-check on the full track.",
      "body": "Average transient strength is 0.76 and crest factor is 18.6 dB, so attacks are not crushed. Speaker translation scores 80 and bass translation reads 'good'. There is no clipping, and true peak is -3.3 dBTP. The clip is only 9.2 s with a fade-in, so re-check on the full track.",
      "metricLine": "Strong average transient attack",
      "whyItMatters": "With the transients intact, the low-end fixes are a matter of cleanup and centring. No rebuilding of punch is needed.",
      "presetName": null,
      "evidence": [
        {
          "label": "Strong average transient attack",
          "stems": null,
          "value": 0.7619,
          "metric": "phase1.transients.avg_transient_strength",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Wide peak-to-RMS ratio; dynamics not squashed",
          "stems": null,
          "value": 18.6,
          "metric": "phase1.crest_factor",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Good speaker translation",
          "stems": null,
          "value": 80.06,
          "metric": "phase9.playback.speaker_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Ample true-peak headroom",
          "stems": null,
          "value": -3.33,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -6,
            -1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-08",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "stereo_phase",
      "confidence": 0.75,
      "priorityScore": 20,
      "impact": "med",
      "chartType": null,
      "headline": "No polarity inversion; headphone and speaker translation good",
      "summary": "Correlation is positive, so there is no inverted-polarity element to hunt down. Headphone (83) and speaker (80) translation scores are good, the mix is crossfeed safe, and bass translation is rated good. The problem is decorrelation and balance, not a broken phase relationship.",
      "body": "Correlation is positive, so there is no inverted-polarity element to hunt down. Headphone (83) and speaker (80) translation scores are good, the mix is crossfeed safe, and bass translation is rated good. The problem is decorrelation and balance, not a broken phase relationship.",
      "metricLine": "Positive correlation means phase-safe",
      "whyItMatters": "With no polarity flip, the fix is modest narrowing and rebalancing rather than a forensic hunt for an inverted layer.",
      "presetName": null,
      "evidence": [
        {
          "label": "Positive correlation means phase-safe",
          "stems": null,
          "value": 0.11774036910481339,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Headphone compatibility",
          "stems": null,
          "value": 82.8795008071755,
          "metric": "phase9.playback.headphone_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Speaker translation",
          "stems": null,
          "value": 80.06433855742216,
          "metric": "phase9.playback.speaker_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-22",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "dynamics",
      "confidence": 0.75,
      "priorityScore": 20,
      "impact": "med",
      "chartType": null,
      "headline": "Transients are punchy — strength 0.76",
      "summary": "Average transient strength is 0.76, so derived attack quality is 'punchy' and sits inside the 0.5-0.8 target. There is no sign of squashed attacks. Only 17 transients were detected in 9.2 s (1.8/s), so hits are sparse but each lands hard. Keep compressor attacks at 20-30 ms.",
      "body": "Average transient strength is 0.76, so derived attack quality is 'punchy' and sits inside the 0.5-0.8 target. There is no sign of squashed attacks. Only 17 transients were detected in 9.2 s (1.8/s), so hits are sparse but each lands hard. Keep compressor attacks at 20-30 ms.",
      "metricLine": "Transient strength — punchy",
      "whyItMatters": "Punch is already there, so any added compression must use slow attacks (20-30 ms) or parallel blending to avoid losing it.",
      "presetName": null,
      "evidence": [
        {
          "label": "Transient strength — punchy",
          "stems": null,
          "value": 0.7618884444236755,
          "metric": "phase1.transients.avg_transient_strength",
          "delta_pct": null,
          "expected_range": [
            0.5,
            0.8
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Transient density (sparse)",
          "stems": null,
          "value": 1.8435729461756374,
          "metric": "phase1.transients.transients_per_second",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        },
        {
          "label": "Transients detected in clip",
          "stems": null,
          "value": 17,
          "metric": "phase1.transients.transient_count",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-16",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "frequency_balance",
      "confidence": 0.7,
      "priorityScore": 20,
      "impact": "med",
      "chartType": null,
      "headline": "Sub-bass is controlled and the tonal centre is in the balanced range",
      "summary": "Sub-bass (-37.4 dB) sits 4.7 dB under bass (-32.8 dB), so it is felt rather than heard. The spectral centroid of 1900 Hz lands in the 1500-2500 Hz balanced window. That centroid reflects concentrated 500 Hz-2 kHz energy and does not mean the top end is healthy.",
      "body": "Sub-bass (-37.4 dB) sits 4.7 dB under bass (-32.8 dB), so it is felt rather than heard. The spectral centroid of 1900 Hz lands in the 1500-2500 Hz balanced window. That centroid reflects concentrated 500 Hz-2 kHz energy and does not mean the top end is healthy.",
      "metricLine": "Sub-bass 4.7 dB under bass — controlled",
      "whyItMatters": "A controlled sub under a dominant bass band is the right foundation. The fixes are in the low-mids and the top end, not the sub.",
      "presetName": null,
      "evidence": [
        {
          "label": "Sub-bass 4.7 dB under bass — controlled",
          "stems": null,
          "value": -37.44,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Bass is the dominant low anchor",
          "stems": null,
          "value": -32.77,
          "metric": "phase1.bands.bass",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Centroid in balanced range",
          "stems": null,
          "value": 1900.52,
          "metric": "phase1.spectral_centroid_hz",
          "delta_pct": null,
          "expected_range": [
            1500,
            2500
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-27",
      "analysisId": "sample",
      "specialist": "stereo_field",
      "promptVersion": "stereo_field@1.0.0",
      "model": "claude-cli",
      "severity": "win",
      "category": "playback",
      "confidence": 0.7,
      "priorityScore": 20,
      "impact": "med",
      "chartType": null,
      "headline": "Translates well on headphones and speakers",
      "summary": "Headphone score is 83 and speaker score is 80. The mix is crossfeed-safe and bass translation is rated good. The stereo problems are about balance and width, not playback-system breakage, so fixing pans should not cost translation.",
      "body": "Headphone score is 83 and speaker score is 80. The mix is crossfeed-safe and bass translation is rated good. The stereo problems are about balance and width, not playback-system breakage, so fixing pans should not cost translation.",
      "metricLine": "Headphone compatibility",
      "whyItMatters": "Translation is already solid, so you can re-pan and widen without starting the mix over.",
      "presetName": null,
      "evidence": [
        {
          "label": "Headphone compatibility",
          "stems": null,
          "value": 82.88,
          "metric": "phase9.playback.headphone_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Speaker translation",
          "stems": null,
          "value": 80.06,
          "metric": "phase9.playback.speaker_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  }
];
