/* GENERATED by scripts/gen-sample-report.mjs — do not edit by hand.
 * Source: demo snapshot (spectr-demo-snapshot/v1, exported 2026-10-01T15:49:27.3607515+00:00),
 * demo track "Sample track" (curated). Real analyzer
 * output: 20 of 148 verdicts kept (Triage-routed specialists + measured), clustered into 14 findings.
 * Excluded (contradicted in the same report):
 *   - rule_engine.bpm_genre_match: BPM 120 outside modern_trance range — genre auto-detected as trance; the tempo is right for the track, the genre guess is not
 *   - frequency_balance: Mix is overly bright and thin (spectral centroid 3199 Hz) — contradicted by the same report measuring a dominant sub-bass and missing air
 *   - frequency_balance: 92 hard-clipped samples at master output — duplicate of the Dynamics/Loudness clipping finding (a different evidence row kept it out of that cluster)
 *   - dynamics: Healthy crest factor but could use more punch — contradicted by the over-compression findings (narrow loudness range, squashed dynamics)
 * Regenerate: node scripts/gen-sample-report.mjs <snapshot.json> */
import type { VerdictDto } from '../../../api/types';

export interface SampleCorroboration {
  specialist: string;
  headline: string;
}

export interface SampleFinding {
  verdict: VerdictDto;
  /** Other specialists that independently flagged the same measurement. */
  corroboratedBy: SampleCorroboration[];
}

export interface SampleMeta {
  title: string;
  artist: string | null;
  credit: string | null;
  genre: string | null;
  key: string | null;
  grade: string;
  score: number;
  lufs: number | null;
  truePeakDb: number | null;
  crestFactorDb: number | null;
  loudnessRangeLu: number | null;
  stereoCorrelation: number | null;
  specialistsRun: string[];
  verdictsInSnapshot: number;
}

export const SAMPLE_META: SampleMeta = {
  "title": "Sample track",
  "artist": null,
  "credit": "Sample analysis of a demo track, so you can explore every SPECTR feature.",
  "genre": null,
  "key": "A# minor",
  "grade": "D",
  "score": 69,
  "lufs": -8.9,
  "truePeakDb": 0.4,
  "crestFactorDb": 10.1,
  "loudnessRangeLu": 2,
  "stereoCorrelation": 0.88,
  "specialistsRun": [
    "loudness",
    "frequency_balance",
    "dynamics"
  ],
  "verdictsInSnapshot": 148
};

export const SAMPLE_FINDINGS: SampleFinding[] = [
  {
    "verdict": {
      "id": "sample-11",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "severe",
      "category": "clipping",
      "confidence": 1,
      "priorityScore": 180,
      "impact": "med",
      "chartType": null,
      "headline": "Master output clipping detected — 92 hard-clipped samples",
      "summary": "92 samples are hard-clipped at the master output. This creates audible distortion and is an immediate red flag for distributors. True peak at +0.4 dBTP exceeds streaming platform limits (must be below -1.0 dBTP).",
      "body": "92 samples are hard-clipped at the master output. This creates audible distortion and is an immediate red flag for distributors. True peak at +0.4 dBTP exceeds streaming platform limits (must be below -1.0 dBTP).",
      "metricLine": "Clipping detected",
      "whyItMatters": "Hard clipping creates harsh distortion artifacts. Streaming platforms reject uploads above 0 dBTP. Distributors flag clipped masters as unprofessional.",
      "presetName": null,
      "evidence": [
        {
          "label": "Clipping detected",
          "stems": null,
          "value": 1,
          "metric": "phase1.clipping_detected",
          "delta_pct": null,
          "expected_range": [
            0,
            0
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Clipped samples",
          "stems": null,
          "value": 92,
          "metric": "phase1.clipped_sample_count",
          "delta_pct": null,
          "expected_range": [
            0,
            0
          ],
          "frequency_range_hz": null
        },
        {
          "label": "True peak level",
          "stems": null,
          "value": 0.4458105208785902,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -1,
            -0.1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1,
              "release_ms": 100,
              "lookahead_ms": 5,
              "threshold_db": -3
            }
          }
        ],
        "expected_outcome": "Clipping will be eliminated, true peak will stay below -1.0 dBTP for streaming compliance.",
        "ableton_hint": {
          "band": null,
          "device": "Limiter",
          "preset_name": "Ceiling -1.0 dB"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 120,
      "priorityCategoryWeight": 1.5,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "loudness",
        "headline": "92 hard-clipped samples detected at master output"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-03",
      "analysisId": "sample",
      "specialist": "rule_engine.hot_master",
      "promptVersion": "rule_engine@1.0.0",
      "model": "rules",
      "severity": "severe",
      "category": "clipping",
      "confidence": 0.95,
      "priorityScore": 180,
      "impact": "med",
      "chartType": null,
      "headline": "Master pushed too hot (-8.9 LUFS, peaks over)",
      "summary": "Integrated loudness is 5.1 LU above the -14 streaming target for modern_trance, and peaks +0.45 dBTP over the -1.0 ceiling and 92 clipped samples. One cause: the master is too hot.",
      "body": "Integrated loudness is 5.1 LU above the -14 streaming target for modern_trance, and peaks +0.45 dBTP over the -1.0 ceiling and 92 clipped samples. One cause: the master is too hot.",
      "metricLine": "-8.9 LUFS",
      "whyItMatters": "Streaming turns it back down anyway, so the only thing the extra level buys is the distortion. Pull the master down first - the peak and clipping symptoms go with it.",
      "presetName": null,
      "evidence": [
        {
          "label": "-8.9 LUFS",
          "stems": null,
          "value": -8.865184840642165,
          "metric": "phase1.lufs",
          "delta_pct": null,
          "expected_range": [
            -17,
            -11
          ],
          "frequency_range_hz": null
        },
        {
          "label": "+0.45 dBTP",
          "stems": null,
          "value": 0.4458105208785902,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -6,
            -1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "92 samples",
          "stems": null,
          "value": 92,
          "metric": "phase1.clipped_sample_count",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1,
              "release_ms": 100,
              "lookahead_ms": 2
            }
          }
        ],
        "expected_outcome": "Hold true peak at -1.0 dBTP without audible pumping.",
        "ableton_hint": null
      },
      "sources": null,
      "problemId": "clipping.hot_master.0",
      "kind": "fault",
      "source": "rule_engine",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 120,
      "priorityCategoryWeight": 1.5,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "dynamics",
        "headline": "Mix is pushed too loud for streaming — LUFS at -8.9"
      },
      {
        "specialist": "loudness",
        "headline": "Track 5.1 dB too loud for streaming platforms"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-02",
      "analysisId": "sample",
      "specialist": "rule_engine.mud_buildup",
      "promptVersion": "rule_engine@1.0.0",
      "model": "rules",
      "severity": "severe",
      "category": "frequency_balance",
      "confidence": 0.9,
      "priorityScore": 120,
      "impact": "med",
      "chartType": null,
      "headline": "Low-mid buildup (7.9 dB over mid)",
      "summary": "The 200-500 Hz low-mid sits 7.9 dB above the mid band - the signature of a muddy, congested mix.",
      "body": "The 200-500 Hz low-mid sits 7.9 dB above the mid band - the signature of a muddy, congested mix.",
      "metricLine": "low-mid 7.9 dB over mid",
      "whyItMatters": "Excess low-mid masks definition; a subtractive cut opens the mix up.",
      "presetName": null,
      "evidence": [
        {
          "label": "low-mid 7.9 dB over mid",
          "stems": null,
          "value": -36.424827575683594,
          "metric": "phase1.bands.low_mid",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            200,
            500
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -3.9607391357421875,
              "frequency_hz": 300
            }
          }
        ],
        "expected_outcome": "Carve -4.0 dB at 300 Hz to clear low-mid mud.",
        "ableton_hint": null
      },
      "sources": null,
      "problemId": "frequency_balance.mud_buildup.0",
      "kind": "observation",
      "source": "rule_engine",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": true,
      "where": null,
      "refines": null,
      "priorityBase": 120,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "frequency_balance",
        "headline": "Severe low-mid mud buildup (250-500Hz)"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-16",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "loudness",
      "confidence": 1,
      "priorityScore": 98,
      "impact": "med",
      "chartType": null,
      "headline": "True peak exceeds streaming platform limit by 1.4 dB",
      "summary": "True peak at +0.45 dBTP violates all streaming platform standards (Spotify/Apple/YouTube require < -1.0 dBTP). Track will clip/distort on playback and may be rejected by distributors.",
      "body": "True peak at +0.45 dBTP violates all streaming platform standards (Spotify/Apple/YouTube require < -1.0 dBTP). Track will clip/distort on playback and may be rejected by distributors.",
      "metricLine": "True peak level",
      "whyItMatters": "Streaming platforms clip anything above 0 dBTP. Distributors may reject uploads. Your track will sound distorted compared to properly mastered releases.",
      "presetName": null,
      "evidence": [
        {
          "label": "True peak level",
          "stems": null,
          "value": 0.4458105208785902,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -6,
            -1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1.5,
              "release_ms": 100,
              "lookahead_ms": 5,
              "threshold_db": -2
            }
          }
        ],
        "expected_outcome": "True peak will drop below -1.0 dBTP, eliminating inter-sample distortion and ensuring streaming platform acceptance.",
        "ableton_hint": {
          "band": null,
          "device": "Pro-L2 or FabFilter Pro-L",
          "preset_name": "True Peak Limiting -1.5dB"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-19",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "dynamics",
      "confidence": 0.95,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Over-compressed: no dynamic punch remaining",
      "summary": "Crest factor of 10.1 dB indicates severe over-limiting. Track sounds flat and lifeless. Kick and snare have no transient impact. Target 8-12 dB for trance/house to maintain energy while achieving loudness.",
      "body": "Crest factor of 10.1 dB indicates severe over-limiting. Track sounds flat and lifeless. Kick and snare have no transient impact. Target 8-12 dB for trance/house to maintain energy while achieving loudness.",
      "metricLine": "Crest factor (peak minus RMS)",
      "whyItMatters": "Over-limiting destroys the punch and energy that makes house/trance exciting. Listeners hear a wall of sound with no dynamics or emotional impact.",
      "presetName": null,
      "evidence": [
        {
          "label": "Crest factor (peak minus RMS)",
          "stems": null,
          "value": 10.14566566833502,
          "metric": "phase1.crest_factor",
          "delta_pct": null,
          "expected_range": [
            8,
            14
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Loudness range",
          "stems": null,
          "value": 2.034434253109608,
          "metric": "phase1.loudness_range_lu",
          "delta_pct": null,
          "expected_range": [
            4,
            12
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "gain",
            "params": {
              "gain_db": -4
            }
          },
          {
            "type": "compressor",
            "params": {
              "ratio": 2,
              "knee_db": 3,
              "attack_ms": 30,
              "release_ms": 250,
              "threshold_db": -12,
              "makeup_gain_db": 0
            }
          },
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1.5,
              "release_ms": 150,
              "lookahead_ms": 5,
              "threshold_db": -4
            }
          }
        ],
        "expected_outcome": "Transients breathe again. Kick punches through. Track sounds exciting and dynamic while still loud enough for streaming at -14 LUFS.",
        "ableton_hint": {
          "band": null,
          "device": "Glue Compressor + Limiter",
          "preset_name": "Gentle glue 2:1 + transparent limit"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-05",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.93,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Excessive sub-bass dominates entire frequency spectrum",
      "summary": "Sub-bass at -20.0 dB is 24.4 dB ABOVE mid band (-44.3 dB) and 8.8 dB above bass band (-28.8 dB). Should be 15-20 dB below mid for trance. Overwhelming sub will cause muddy, undefined low end and mask everything else.",
      "body": "Sub-bass at -20.0 dB is 24.4 dB ABOVE mid band (-44.3 dB) and 8.8 dB above bass band (-28.8 dB). Should be 15-20 dB below mid for trance. Overwhelming sub will cause muddy, undefined low end and mask everything else.",
      "metricLine": "Sub-bass energy (20-60Hz)",
      "whyItMatters": "Excessive sub-bass overwhelms small speakers, causes low-end smearing, and masks kick/bass definition. Will sound terrible on phone speakers and car systems. Sub should be felt, not heard.",
      "presetName": null,
      "evidence": [
        {
          "label": "Sub-bass energy (20-60Hz)",
          "stems": null,
          "value": -19.979097366333008,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": [
            -60,
            -50
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Sub-bass percentage of total energy",
          "stems": null,
          "value": 43.509758663898204,
          "metric": "phase4.band_energy.sub_bass",
          "delta_pct": null,
          "expected_range": [
            5,
            15
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Ultra-low frequency content (<30Hz)",
          "stems": null,
          "value": 24.90034294128418,
          "metric": "phase1.sub_30_energy",
          "delta_pct": null,
          "expected_range": [
            0,
            10
          ],
          "frequency_range_hz": [
            0,
            30
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.7,
              "slope_db": 24,
              "frequency_hz": 30
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -6,
              "frequency_hz": 40
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -4,
              "frequency_hz": 50
            }
          }
        ],
        "expected_outcome": "Sub-bass drops to felt-not-heard level, allowing bass and mid frequencies to breathe and define the mix.",
        "ableton_hint": {
          "band": 1,
          "device": "EQ Eight",
          "preset_name": "Sub rumble control"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-08",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_collision",
      "confidence": 0.92,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Critical low-end frequency buildup (20-200Hz)",
      "summary": "Sub-bass (43.5%) + bass (38.9%) = 82.4% of total mix energy concentrated in 20-200Hz. This extreme low-end dominance causes smearing, masks definition, and will translate terribly on most playback systems.",
      "body": "Sub-bass (43.5%) + bass (38.9%) = 82.4% of total mix energy concentrated in 20-200Hz. This extreme low-end dominance causes smearing, masks definition, and will translate terribly on most playback systems.",
      "metricLine": "Low-end buildup clash detected",
      "whyItMatters": "82% of mix energy in sub/bass is extreme and will cause severe translation problems. Phone speakers, laptop speakers, and small club systems will completely lose the mix. Professional trance uses…",
      "presetName": null,
      "evidence": [
        {
          "label": "Low-end buildup clash detected",
          "stems": null,
          "value": null,
          "metric": "phase4.clashes",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            20,
            200
          ]
        },
        {
          "label": "Sub-bass dominance",
          "stems": null,
          "value": 43.509758663898204,
          "metric": "phase4.band_energy.sub_bass",
          "delta_pct": null,
          "expected_range": [
            5,
            15
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Bass dominance",
          "stems": null,
          "value": 38.86233518943452,
          "metric": "phase4.band_energy.bass",
          "delta_pct": null,
          "expected_range": [
            20,
            30
          ],
          "frequency_range_hz": [
            60,
            250
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.7,
              "slope_db": 18,
              "frequency_hz": 35
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -5,
              "frequency_hz": 50
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -4,
              "frequency_hz": 100
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -3,
              "frequency_hz": 150
            }
          }
        ],
        "expected_outcome": "Low-end energy reduces from 82% to 40-50%, allowing mid and high frequencies to define the mix with clarity.",
        "ableton_hint": {
          "band": 1,
          "device": "EQ Eight",
          "preset_name": "Low-end cleanup chain"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "frequency_balance",
        "headline": "Low-mid congestion (200-500Hz) - 33.6% of total energy"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-06",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.88,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Bass band overpowering mid frequencies",
      "summary": "Bass at -28.8 dB is 15.5 dB above mid band (-44.3 dB). Target: bass should be similar level to mid (within 3-5 dB) for trance balance. Current ratio creates bottom-heavy, undefined mix lacking presence.",
      "body": "Bass at -28.8 dB is 15.5 dB above mid band (-44.3 dB). Target: bass should be similar level to mid (within 3-5 dB) for trance balance. Current ratio creates bottom-heavy, undefined mix lacking presence.",
      "metricLine": "Bass energy (60-250Hz)",
      "whyItMatters": "Overpowering bass masks lead synths, vocals, and melodic elements. Mix will sound boomy and lack definition. Trance needs balanced bass-to-mid ratio for drive without muddiness.",
      "presetName": null,
      "evidence": [
        {
          "label": "Bass energy (60-250Hz)",
          "stems": null,
          "value": -28.801156997680664,
          "metric": "phase1.bands.bass",
          "delta_pct": null,
          "expected_range": [
            -45,
            -40
          ],
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Bass percentage of total energy",
          "stems": null,
          "value": 38.86233518943452,
          "metric": "phase4.band_energy.bass",
          "delta_pct": null,
          "expected_range": [
            20,
            30
          ],
          "frequency_range_hz": [
            60,
            250
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -4,
              "frequency_hz": 100
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -3,
              "frequency_hz": 150
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -2,
              "frequency_hz": 200
            }
          }
        ],
        "expected_outcome": "Bass foundation maintains weight but no longer masks mid-range leads and melodies.",
        "ableton_hint": {
          "band": 2,
          "device": "EQ Eight",
          "preset_name": "Bass fundamental taming"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-07",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.86,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Missing air and sparkle (6-20kHz band very low)",
      "summary": "Air band at -62.7 dB is 18.4 dB below mid band. Target: 10-12 dB below mid for trance shimmer. Despite bright spectral centroid (3199 Hz), actual high-frequency extension is weak, suggesting harsh upper-mids without true air.",
      "body": "Air band at -62.7 dB is 18.4 dB below mid band. Target: 10-12 dB below mid for trance shimmer. Despite bright spectral centroid (3199 Hz), actual high-frequency extension is weak, suggesting harsh upper-mids without true air.",
      "metricLine": "Air energy (6-20kHz)",
      "whyItMatters": "Modern trance needs air and sparkle for professional sheen. Missing high-frequency extension makes mix sound dull and closed-in despite bright character. Air gives sense of space and polish.",
      "presetName": null,
      "evidence": [
        {
          "label": "Air energy (6-20kHz)",
          "stems": null,
          "value": -62.729026794433594,
          "metric": "phase1.bands.air",
          "delta_pct": null,
          "expected_range": [
            -55,
            -50
          ],
          "frequency_range_hz": [
            6000,
            20000
          ]
        },
        {
          "label": "Air percentage of total energy",
          "stems": null,
          "value": 1.9295081673170031,
          "metric": "phase4.band_energy.air",
          "delta_pct": null,
          "expected_range": [
            5,
            10
          ],
          "frequency_range_hz": [
            6000,
            20000
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_shelf",
            "params": {
              "q": 0.7,
              "gain_db": 3,
              "frequency_hz": 10000
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": 2,
              "frequency_hz": 12000
            }
          }
        ],
        "expected_outcome": "Mix gains sparkle and open-air quality without adding harshness, improving perceived clarity and professional sheen.",
        "ableton_hint": {
          "band": 7,
          "device": "EQ Eight",
          "preset_name": "Air and shimmer"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-20",
      "analysisId": "sample",
      "specialist": "loudness",
      "promptVersion": "loudness@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "playback",
      "confidence": 0.85,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Excessive sub-bass will overwhelm small speakers",
      "summary": "Sub-30Hz energy at 24.9% and sub-bass band at -19.98 dBFS creates problems on consumer playback systems. Phone/laptop speakers cannot reproduce these frequencies and will distort trying.",
      "body": "Sub-30Hz energy at 24.9% and sub-bass band at -19.98 dBFS creates problems on consumer playback systems. Phone/laptop speakers cannot reproduce these frequencies and will distort trying.",
      "metricLine": "Energy below 30 Hz",
      "whyItMatters": "Most listeners hear your track on phones/laptops. Excessive sub-bass causes speaker distortion and muddy low-end translation, making the mix sound unprofessional.",
      "presetName": null,
      "evidence": [
        {
          "label": "Energy below 30 Hz",
          "stems": null,
          "value": 24.90034294128418,
          "metric": "phase1.sub_30_energy",
          "delta_pct": null,
          "expected_range": [
            5,
            15
          ],
          "frequency_range_hz": [
            20,
            30
          ]
        },
        {
          "label": "Sub-bass band level",
          "stems": null,
          "value": -19.979097366333008,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": [
            -30,
            -24
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Bass translation assessment",
          "stems": null,
          "value": null,
          "metric": "phase9.playback.bass_translation",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.707,
              "slope_db": 24,
              "frequency_hz": 35
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -2,
              "frequency_hz": 50
            }
          }
        ],
        "expected_outcome": "Sub-bass tightens up. Mix translates cleanly to phone/laptop speakers without distortion. Kick remains powerful but controlled.",
        "ableton_hint": {
          "band": null,
          "device": "EQ Eight",
          "preset_name": "Sub control: 35Hz HPF + 50Hz cut"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-10",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.84,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Mid-range (500-2kHz) severely underrepresented",
      "summary": "Mid band at -44.3 dB is weakest of primary bands (should dominate for trance). Only 21.8% of total energy vs 43.5% sub, 38.9% bass, 33.6% low-mid. Leads and melodies lack body and cut-through power.",
      "body": "Mid band at -44.3 dB is weakest of primary bands (should dominate for trance). Only 21.8% of total energy vs 43.5% sub, 38.9% bass, 33.6% low-mid. Leads and melodies lack body and cut-through power.",
      "metricLine": "Mid-range percentage of total energy",
      "whyItMatters": "500-2kHz is where leads, vocals, and melodies live. Current 21.8% energy means these elements are buried under low-end rumble. Trance needs strong mids for emotional impact and melodic definition.",
      "presetName": null,
      "evidence": [
        {
          "label": "Mid-range percentage of total energy",
          "stems": null,
          "value": 21.806884503677082,
          "metric": "phase4.band_energy.mid",
          "delta_pct": null,
          "expected_range": [
            35,
            45
          ],
          "frequency_range_hz": [
            500,
            2000
          ]
        },
        {
          "label": "Mid-range relative level",
          "stems": null,
          "value": -44.34630584716797,
          "metric": "phase1.bands.mid",
          "delta_pct": null,
          "expected_range": [
            -35,
            -30
          ],
          "frequency_range_hz": [
            500,
            2000
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": 3,
              "frequency_hz": 800
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": 4,
              "frequency_hz": 1200
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": 2,
              "frequency_hz": 1800
            }
          }
        ],
        "expected_outcome": "Mid-range gains presence and body, allowing leads and melodies to cut through and dominate the mix as intended.",
        "ableton_hint": {
          "band": 4,
          "device": "EQ Eight",
          "preset_name": "Mid presence boost"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-13",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "dynamics",
      "confidence": 0.75,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Narrow loudness range indicates over-compression",
      "summary": "Loudness range at 2.0 LU is very narrow (target: 3-6 LU). This suggests heavy compression/limiting has reduced dynamic variation, making the mix sound flat and fatiguing despite adequate crest factor.",
      "body": "Loudness range at 2.0 LU is very narrow (target: 3-6 LU). This suggests heavy compression/limiting has reduced dynamic variation, making the mix sound flat and fatiguing despite adequate crest factor.",
      "metricLine": "Loudness range",
      "whyItMatters": "Narrow loudness range makes the entire track sound the same level, destroying the natural ebb and flow. Listeners fatigue quickly when everything is constantly loud.",
      "presetName": null,
      "evidence": [
        {
          "label": "Loudness range",
          "stems": null,
          "value": 2.034434253109608,
          "metric": "phase1.loudness_range_lu",
          "delta_pct": null,
          "expected_range": [
            3,
            6
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Integrated LUFS",
          "stems": null,
          "value": -8.865184840642165,
          "metric": "phase1.lufs",
          "delta_pct": null,
          "expected_range": [
            -10,
            -8
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "compressor",
            "params": {
              "ratio": 2,
              "knee_db": 3,
              "attack_ms": 30,
              "release_ms": 200,
              "threshold_db": -12,
              "makeup_gain_db": 0
            }
          }
        ],
        "expected_outcome": "Loudness range will increase to 3-4 LU, restoring micro-dynamics and reducing listener fatigue.",
        "ableton_hint": {
          "band": null,
          "device": "Glue Compressor",
          "preset_name": "Gentle glue 2:1"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": [
      {
        "specialist": "rule_engine.over_compression",
        "headline": "Heavily compressed - dynamics squashed"
      }
    ]
  },
  {
    "verdict": {
      "id": "sample-14",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "dynamics",
      "confidence": 0.7,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Peak level too close to 0 dBFS — leaves no safety margin",
      "summary": "Peak level at effectively 0 dBFS (8.7e-09 dBFS ≈ 0 dB) combined with true peak overshoot (+0.4 dBTP) indicates limiting ceiling is set too high. Need -3 to -1 dBFS target peak for inter-sample peak headroom.",
      "body": "Peak level at effectively 0 dBFS (8.7e-09 dBFS ≈ 0 dB) combined with true peak overshoot (+0.4 dBTP) indicates limiting ceiling is set too high. Need -3 to -1 dBFS target peak for inter-sample peak headroom.",
      "metricLine": "Peak level dBFS",
      "whyItMatters": "Peak at 0 dBFS with true peak overshoot means inter-sample peaks are clipping during D/A conversion. DACs reconstruct the waveform above 0 dBFS, causing distortion.",
      "presetName": null,
      "evidence": [
        {
          "label": "Peak level dBFS",
          "stems": null,
          "value": 8.685890352395823e-9,
          "metric": "phase1.peak_dbfs",
          "delta_pct": null,
          "expected_range": [
            -3,
            -1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "True peak dBTP",
          "stems": null,
          "value": 0.4458105208785902,
          "metric": "phase1.true_peak_db",
          "delta_pct": null,
          "expected_range": [
            -1,
            -0.1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1.5,
              "release_ms": 100,
              "lookahead_ms": 5,
              "threshold_db": -4
            }
          }
        ],
        "expected_outcome": "Peak level will target -1.5 dBFS, true peak will stay below -1.0 dBTP, preventing inter-sample clipping.",
        "ableton_hint": {
          "band": null,
          "device": "Limiter",
          "preset_name": "Ceiling -1.5 dB safety"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-15",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "minor",
      "category": "mono_compatibility",
      "confidence": 0.95,
      "priorityScore": 42,
      "impact": "med",
      "chartType": null,
      "headline": "Excellent mono compatibility — phase relationship solid",
      "summary": "Mono compatibility at 96.9% and stereo correlation at 0.877 indicate excellent phase coherence. Mix will translate well to mono playback systems without phase cancellation issues.",
      "body": "Mono compatibility at 96.9% and stereo correlation at 0.877 indicate excellent phase coherence. Mix will translate well to mono playback systems without phase cancellation issues.",
      "metricLine": "Mono compatibility",
      "whyItMatters": "High mono compatibility ensures your mix doesn't lose energy or frequency content when played in mono (clubs, smartphones, some streaming scenarios).",
      "presetName": null,
      "evidence": [
        {
          "label": "Mono compatibility",
          "stems": null,
          "value": 0.9687822310741312,
          "metric": "phase1.mono_compatibility",
          "delta_pct": null,
          "expected_range": [
            0.9,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Stereo correlation",
          "stems": null,
          "value": 0.8771523050359941,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0.7,
            0.95
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  }
];
