/* GENERATED by scripts/gen-sample-report.mjs — do not edit by hand.
 * Source: demo snapshot (spectr-demo-snapshot/v1, exported 2026-10-01T03:29:01.6833495+00:00),
 * sample track "Neon Meridian" (curated demo). Real analyzer
 * output: 13 of 13 verdicts kept, clustered into 13 findings.
 * Excluded (contradicted in the same report):

 * Regenerate: node scripts/gen-sample-report.mjs <snapshot.json> */
import type { VerdictDto } from '../../../api/types';

export interface SampleCorroboration {
  specialist: string;
  headline: string;
}

export interface SampleFinding {
  verdict: VerdictDto;
  /** Other specialists that independently flagged the same measurement. */
  corroboratedBy: SampleCorroboration[];
}

export interface SampleMeta {
  title: string;
  artist: string | null;
  genre: string | null;
  key: string | null;
  grade: string;
  score: number;
  lufs: number | null;
  truePeakDb: number | null;
  crestFactorDb: number | null;
  loudnessRangeLu: number | null;
  stereoCorrelation: number | null;
  specialistsRun: string[];
  pipelineVersion: string;
  verdictsInSnapshot: number;
}

export const SAMPLE_META: SampleMeta = {
  "title": "Neon Meridian",
  "artist": null,
  "genre": "trance",
  "key": "D major",
  "grade": "F",
  "score": 38,
  "lufs": -13,
  "truePeakDb": -1,
  "crestFactorDb": 12.5,
  "loudnessRangeLu": 2.7,
  "stereoCorrelation": 0.75,
  "specialistsRun": [
    "low_end",
    "dynamics",
    "stereo_phase",
    "frequency_balance"
  ],
  "pipelineVersion": "2.2.0",
  "verdictsInSnapshot": 13
};

export const SAMPLE_FINDINGS: SampleFinding[] = [
  {
    "verdict": {
      "id": "sample-08",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "mono_compatibility",
      "confidence": 0.9,
      "priorityScore": 98,
      "impact": "med",
      "chartType": null,
      "headline": "Moderate speaker translation — low end may overwhelm small speakers",
      "summary": "Speaker compatibility at 56% indicates the mix doesn't translate well to smaller playback systems. Combined with excessive sub-bass energy (-18.6 dB), the low end will overpower phone speakers, laptops, and Bluetooth devices.",
      "body": "Speaker compatibility at 56% indicates the mix doesn't translate well to smaller playback systems. Combined with excessive sub-bass energy (-18.6 dB), the low end will overpower phone speakers, laptops, and Bluetooth devices.",
      "metricLine": "Speaker translation (56% = moderate issues)",
      "whyItMatters": "Most listeners hear your track on phones, laptops, or Bluetooth speakers. Excessive sub-bass overwhelms these systems, making the mix sound muddy and boomy instead of tight and punchy.",
      "presetName": null,
      "evidence": [
        {
          "label": "Speaker translation (56% = moderate issues)",
          "stems": null,
          "value": 56.06231603771448,
          "metric": "phase9.playback.speaker_score",
          "delta_pct": null,
          "expected_range": [
            80,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Sub-bass level (-18.6 dB = excessive)",
          "stems": null,
          "value": -18.556116104125977,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": [
            -30,
            -24
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Sub-30Hz energy (18.7 = very high)",
          "stems": null,
          "value": 18.683517456054688,
          "metric": "phase1.sub_30_energy",
          "delta_pct": null,
          "expected_range": [
            0,
            10
          ],
          "frequency_range_hz": [
            0,
            30
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.7,
              "slope_db": 24,
              "frequency_hz": 35
            }
          }
        ],
        "expected_outcome": "Low end becomes tighter and controlled, translating better to small speakers without losing club impact.",
        "ableton_hint": {
          "band": null,
          "device": "EQ Eight",
          "preset_name": "Sub cleanup 35Hz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-03",
      "analysisId": "sample",
      "specialist": "low_end",
      "promptVersion": "low_end@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "low_end",
      "confidence": 0.95,
      "priorityScore": 91,
      "impact": "med",
      "chartType": null,
      "headline": "Excessive sub-bass energy overwhelming mix",
      "summary": "Sub-bass at 37.2 dB is severely elevated, dominating the low end and eating headroom. This energy is felt but not heard, wasting power on frequencies that don't translate to small speakers. Combined with bass at 36.2 dB, low end is unbalanced and boomy.",
      "body": "Sub-bass at 37.2 dB is severely elevated, dominating the low end and eating headroom. This energy is felt but not heard, wasting power on frequencies that don't translate to small speakers. Combined with bass at 36.2 dB, low end is unbalanced and boomy.",
      "metricLine": "Sub-bass energy (20-60 Hz)",
      "whyItMatters": "Excessive sub wastes headroom, limits loudness potential, and creates boomy mixes that don't translate to small speakers or club systems where sub is often mono-summed.",
      "presetName": null,
      "evidence": [
        {
          "label": "Sub-bass energy (20-60 Hz)",
          "stems": null,
          "value": 37.238987905218096,
          "metric": "phase4.band_energy.sub_bass",
          "delta_pct": null,
          "expected_range": [
            25,
            32
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        },
        {
          "label": "Bass energy (60-250 Hz)",
          "stems": null,
          "value": 36.24838757259374,
          "metric": "phase4.band_energy.bass",
          "delta_pct": null,
          "expected_range": [
            32,
            40
          ],
          "frequency_range_hz": [
            60,
            250
          ]
        },
        {
          "label": "Sub-bass dBFS level",
          "stems": null,
          "value": -18.556116104125977,
          "metric": "phase1.bands.sub_bass",
          "delta_pct": null,
          "expected_range": [
            -28,
            -22
          ],
          "frequency_range_hz": [
            20,
            60
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "q": 0.707,
              "slope_db": 24,
              "frequency_hz": 30
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -4,
              "frequency_hz": 45
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -2,
              "frequency_hz": 80
            }
          }
        ],
        "expected_outcome": "Sub-bass will be felt appropriately without overwhelming the mix, freeing headroom and improving clarity on all playback systems.",
        "ableton_hint": {
          "band": 1,
          "device": "EQ Eight",
          "preset_name": "Sub control - HP30 + cut45"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-04",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "dynamics",
      "confidence": 0.95,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Over-compressed — mix lacks punch and transient definition",
      "summary": "Crest factor at 12.5 dB is acceptable but transient strength of 1.31 indicates severely squashed dynamics. Attack quality is well above 0.6 (punchy range), yet the high transient strength suggests over-processing. The mix sounds lifeless despite loud peaks — transients are being destroyed by…",
      "body": "Crest factor at 12.5 dB is acceptable but transient strength of 1.31 indicates severely squashed dynamics. Attack quality is well above 0.6 (punchy range), yet the high transient strength suggests over-processing. The mix sounds lifeless despite loud peaks — transients are being destroyed by…",
      "metricLine": "Crest factor (Peak − RMS) in dB",
      "whyItMatters": "Over-compressed mixes sound flat and fatiguing despite being loud. The kick doesn't punch, the drop doesn't hit, and listeners lose interest quickly because everything sits at the same energy level.",
      "presetName": null,
      "evidence": [
        {
          "label": "Crest factor (Peak − RMS) in dB",
          "stems": null,
          "value": 12.528889128915104,
          "metric": "phase1.crest_factor",
          "delta_pct": null,
          "expected_range": [
            8,
            12
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Average transient strength (0–1 scale)",
          "stems": null,
          "value": 1.3057291507720947,
          "metric": "phase1.transients.avg_transient_strength",
          "delta_pct": null,
          "expected_range": [
            0.5,
            0.8
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Transient density (hits per second)",
          "stems": null,
          "value": 7.617938804257609,
          "metric": "phase1.transients.transients_per_second",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master Bus",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "compressor",
            "params": {
              "ratio": 3,
              "knee_db": 3,
              "attack_ms": 30,
              "release_ms": 150,
              "threshold_db": -6,
              "makeup_gain_db": 0
            }
          },
          {
            "type": "limiter",
            "params": {
              "ceiling_db": -1,
              "release_ms": 50,
              "lookahead_ms": 2,
              "threshold_db": -3
            }
          }
        ],
        "expected_outcome": "Kick and snare will punch through with clarity, transients will crack, and the mix will sound alive rather than fatiguing.",
        "ableton_hint": {
          "band": null,
          "device": "Glue Compressor",
          "preset_name": "Master bus glue 3:1 30ms"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-06",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "stereo_field",
      "confidence": 0.95,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Mix too narrow — stereo correlation 0.75 lacks width for trance",
      "summary": "Stereo correlation at 0.75 indicates a very narrow mix with minimal stereo information (width: 0.13). Trance requires wide pads and supersaws (target correlation: 0.3-0.6). Current mix sounds flat and amateur with elements fighting in the center.",
      "body": "Stereo correlation at 0.75 indicates a very narrow mix with minimal stereo information (width: 0.13). Trance requires wide pads and supersaws (target correlation: 0.3-0.6). Current mix sounds flat and amateur with elements fighting in the center.",
      "metricLine": "Stereo correlation (0.75 = too narrow for trance)",
      "whyItMatters": "Narrow mixes sound flat and amateur in trance. Professional trance has wide supersaws and pads that fill the stereo field. This mix lacks that dimension and sounds congested in the center.",
      "presetName": null,
      "evidence": [
        {
          "label": "Stereo correlation (0.75 = too narrow for trance)",
          "stems": null,
          "value": 0.7532607037568414,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0.3,
            0.6
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Stereo width (0.13 = minimal stereo content)",
          "stems": null,
          "value": 0.12959551811218262,
          "metric": "phase1.stereo_width",
          "delta_pct": null,
          "expected_range": [
            0.4,
            0.8
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Width consistency (27% = unstable stereo image)",
          "stems": null,
          "value": 27.409946580871207,
          "metric": "phase9.spatial.width_consistency",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "stereo_width",
            "params": {
              "width_pct": 130
            }
          }
        ],
        "expected_outcome": "Mix gains stereo interest with wider pads and atmosphere while maintaining mono compatibility.",
        "ableton_hint": {
          "band": null,
          "device": "Utility",
          "preset_name": "Width 130%"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-11",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.92,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Low-mid mud buildup — mix clarity destroyed",
      "summary": "Low-mid band at -35.0 dB is only 2.9 dB below mid band at -37.9 dB, far too close for trance clarity. Should be 5-8 dB lower. This is the primary cause of muddy, undefined sound in 250-500Hz range.",
      "body": "Low-mid band at -35.0 dB is only 2.9 dB below mid band at -37.9 dB, far too close for trance clarity. Should be 5-8 dB lower. This is the primary cause of muddy, undefined sound in 250-500Hz range.",
      "metricLine": "Low-mid energy (250-500Hz)",
      "whyItMatters": "250-500Hz is the mud zone where clarity dies. Multiple elements pile up here causing boomy, undefined, amateur sound. This is the #1 amateur mixing mistake in trance.",
      "presetName": null,
      "evidence": [
        {
          "label": "Low-mid energy (250-500Hz)",
          "stems": null,
          "value": -34.96110534667969,
          "metric": "phase1.bands.low_mid",
          "delta_pct": null,
          "expected_range": [
            -45,
            -38
          ],
          "frequency_range_hz": [
            250,
            500
          ]
        },
        {
          "label": "Mid energy (500-2kHz)",
          "stems": null,
          "value": -37.88075256347656,
          "metric": "phase1.bands.mid",
          "delta_pct": null,
          "expected_range": [
            -35,
            -25
          ],
          "frequency_range_hz": [
            500,
            2000
          ]
        },
        {
          "label": "Low-mid relative energy",
          "stems": null,
          "value": 22.351035009752586,
          "metric": "phase4.band_energy.low_mid",
          "delta_pct": null,
          "expected_range": [
            12,
            18
          ],
          "frequency_range_hz": [
            250,
            500
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": -4,
              "frequency_hz": 280
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.5,
              "gain_db": -3,
              "frequency_hz": 350
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": -2,
              "frequency_hz": 450
            }
          }
        ],
        "expected_outcome": "Low-mid band will drop 5-8 dB below mid band, restoring clarity and definition. Bass and kick will separate, leads will cut through.",
        "ableton_hint": {
          "band": 3,
          "device": "EQ Eight",
          "preset_name": "Mud sweep: -4dB 280Hz, -3dB 350Hz, -2dB 450Hz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-02",
      "analysisId": "sample",
      "specialist": "rule_engine.modal_ambiguity",
      "promptVersion": "rule_engine@1.0.0",
      "model": "rules",
      "severity": "moderate",
      "category": "harmonic",
      "confidence": 0.9,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Ambiguous key: D major vs D minor",
      "summary": "The top two key fits are within 0.039; the track reads as ambiguous between D major and D minor (often relative major/minor).",
      "body": "The top two key fits are within 0.039; the track reads as ambiguous between D major and D minor (often relative major/minor).",
      "metricLine": "top-2 margin 0.039",
      "whyItMatters": "An ambiguous tonal centre makes auto key + harmonic-mixing labels unreliable; confirm the key by ear.",
      "presetName": null,
      "evidence": [
        {
          "label": "top-2 margin 0.039",
          "stems": null,
          "value": 0.6231028105128515,
          "metric": "phase1.key_estimate.confidence",
          "delta_pct": null,
          "expected_range": [
            0.5,
            1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": "harmonic.modal_ambiguity.0",
      "kind": "observation",
      "source": "rule_engine",
      "dataTier": "audio_only",
      "fixable": false,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-12",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.88,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Missing air and sparkle — mix sounds dark and closed",
      "summary": "Air band at -61.6 dB is 23.7 dB below mid band at -37.9 dB, well beyond the target 10-12 dB difference. Spectral centroid at 3320 Hz is acceptable but air energy is critically low, removing trance's signature shimmer.",
      "body": "Air band at -61.6 dB is 23.7 dB below mid band at -37.9 dB, well beyond the target 10-12 dB difference. Spectral centroid at 3320 Hz is acceptable but air energy is critically low, removing trance's signature shimmer.",
      "metricLine": "Air energy (6-20kHz)",
      "whyItMatters": "Modern trance requires air and sparkle from supersaws and hi-hats. Without it, the mix sounds dull, distant, and unprofessional. Air is what makes trance sound open and exciting.",
      "presetName": null,
      "evidence": [
        {
          "label": "Air energy (6-20kHz)",
          "stems": null,
          "value": -61.592838287353516,
          "metric": "phase1.bands.air",
          "delta_pct": null,
          "expected_range": [
            -50,
            -42
          ],
          "frequency_range_hz": [
            6000,
            20000
          ]
        },
        {
          "label": "Spectral centroid (brightness)",
          "stems": null,
          "value": 3320.1755852087636,
          "metric": "phase1.spectral_centroid_hz",
          "delta_pct": null,
          "expected_range": [
            2500,
            4000
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Air relative energy",
          "stems": null,
          "value": -4.6622538939222915,
          "metric": "phase4.band_energy.air",
          "delta_pct": null,
          "expected_range": [
            8,
            15
          ],
          "frequency_range_hz": [
            6000,
            20000
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_shelf",
            "params": {
              "q": 0.7,
              "gain_db": 3,
              "frequency_hz": 10000
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1,
              "gain_db": 2,
              "frequency_hz": 8000
            }
          },
          {
            "type": "high_shelf",
            "params": {
              "q": 0.5,
              "gain_db": 2,
              "frequency_hz": 14000
            }
          }
        ],
        "expected_outcome": "Air band will rise to proper level relative to mid, adding trance shimmer and professional sparkle without harshness.",
        "ableton_hint": {
          "band": 7,
          "device": "EQ Eight",
          "preset_name": "Air boost: +3dB shelf 10kHz, +2dB 8kHz, +2dB shelf 14kHz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-07",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "stereo_phase",
      "confidence": 0.85,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Unstable stereo width causes drifting image",
      "summary": "Stereo width consistency at 27% means the stereo image is shifting dramatically throughout the track. This creates an unprofessional, unstable soundstage. Width changes should be deliberate (automation) rather than accidental drift.",
      "body": "Stereo width consistency at 27% means the stereo image is shifting dramatically throughout the track. This creates an unprofessional, unstable soundstage. Width changes should be deliberate (automation) rather than accidental drift.",
      "metricLine": "Width consistency (27% = highly unstable)",
      "whyItMatters": "An unstable stereo image is distracting and unprofessional. Listeners perceive the soundstage as shifting or wobbling. Width changes should be intentional (builds/drops) not accidental.",
      "presetName": null,
      "evidence": [
        {
          "label": "Width consistency (27% = highly unstable)",
          "stems": null,
          "value": 27.409946580871207,
          "metric": "phase9.spatial.width_consistency",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Average stereo width (0.13 = narrow baseline)",
          "stems": null,
          "value": 0.12959551811218262,
          "metric": "phase1.stereo_width",
          "delta_pct": null,
          "expected_range": [
            0.4,
            0.8
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "stereo_width",
            "params": {
              "width_pct": 120
            }
          }
        ],
        "expected_outcome": "Stereo image becomes stable and consistent throughout the track with controlled width variations.",
        "ableton_hint": {
          "band": null,
          "device": "Utility",
          "preset_name": "Stable width 120%"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-13",
      "analysisId": "sample",
      "specialist": "frequency_balance",
      "promptVersion": "frequency_balance@1.1.0",
      "model": "claude-sonnet-4-5",
      "severity": "moderate",
      "category": "frequency_balance",
      "confidence": 0.82,
      "priorityScore": 70,
      "impact": "med",
      "chartType": null,
      "headline": "Upper-mid presence insufficient — lacks clarity and attack",
      "summary": "Upper-mid band at -42.4 dB is 4.5 dB below mid band at -37.9 dB, slightly more than the ideal 3-4 dB difference. While not severely scooped, increasing upper-mid presence would improve lead definition and transient clarity.",
      "body": "Upper-mid band at -42.4 dB is 4.5 dB below mid band at -37.9 dB, slightly more than the ideal 3-4 dB difference. While not severely scooped, increasing upper-mid presence would improve lead definition and transient clarity.",
      "metricLine": "Upper-mid energy (2-6kHz)",
      "whyItMatters": "Upper-mids provide clarity, attack, and definition in trance. Slightly boosting this range helps leads cut through the mix and improves transient definition without causing harshness.",
      "presetName": null,
      "evidence": [
        {
          "label": "Upper-mid energy (2-6kHz)",
          "stems": null,
          "value": -42.405521392822266,
          "metric": "phase1.bands.upper_mid",
          "delta_pct": null,
          "expected_range": [
            -40,
            -32
          ],
          "frequency_range_hz": [
            2000,
            6000
          ]
        },
        {
          "label": "Presence energy (4-6kHz)",
          "stems": null,
          "value": -47.4234504699707,
          "metric": "phase1.bands.presence",
          "delta_pct": null,
          "expected_range": [
            -45,
            -38
          ],
          "frequency_range_hz": [
            4000,
            6000
          ]
        },
        {
          "label": "Upper-mid relative energy",
          "stems": null,
          "value": 9.975514784098298,
          "metric": "phase4.band_energy.high_mid",
          "delta_pct": null,
          "expected_range": [
            12,
            18
          ],
          "frequency_range_hz": [
            2000,
            6000
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "Master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.5,
              "gain_db": 2,
              "frequency_hz": 2500
            }
          },
          {
            "type": "peaking_eq",
            "params": {
              "q": 1.2,
              "gain_db": 1.5,
              "frequency_hz": 4000
            }
          }
        ],
        "expected_outcome": "Lead synths and transients will gain clarity and definition without harshness. Attack and articulation will improve.",
        "ableton_hint": {
          "band": 5,
          "device": "EQ Eight",
          "preset_name": "Presence boost: +2dB 2.5kHz, +1.5dB 4kHz"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 70,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-01",
      "analysisId": "sample",
      "specialist": "rule_engine.sub_rumble",
      "promptVersion": "rule_engine@1.0.0",
      "model": "rules",
      "severity": "minor",
      "category": "low_end",
      "confidence": 0.9,
      "priorityScore": 39,
      "impact": "med",
      "chartType": null,
      "headline": "Sub-30 Hz rumble wasting headroom",
      "summary": "Energy below 30 Hz is 41% of the 20-200 Hz low band — mostly inaudible rumble eating limiter headroom.",
      "body": "Energy below 30 Hz is 41% of the 20-200 Hz low band — mostly inaudible rumble eating limiter headroom.",
      "metricLine": "41% of low band",
      "whyItMatters": "Infrasonic content below ~30 Hz is rarely audible but costs headroom; a steep high-pass recovers it.",
      "presetName": null,
      "evidence": [
        {
          "label": "41% of low band",
          "stems": null,
          "value": 18.683517456054688,
          "metric": "phase1.sub_30_energy",
          "delta_pct": null,
          "expected_range": null,
          "frequency_range_hz": [
            0,
            30
          ]
        }
      ],
      "fix": {
        "target": {
          "name": "master",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "high_pass",
            "params": {
              "slope_db": 24,
              "frequency_hz": 30
            }
          }
        ],
        "expected_outcome": "High-pass at 30 Hz to clear sub rumble.",
        "ableton_hint": null
      },
      "sources": null,
      "problemId": "low_end.sub_rumble.0",
      "kind": "fault",
      "source": "rule_engine",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": true,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1.3,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-05",
      "analysisId": "sample",
      "specialist": "dynamics",
      "promptVersion": "dynamics@2.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "minor",
      "category": "dynamics",
      "confidence": 0.75,
      "priorityScore": 21,
      "impact": "med",
      "chartType": null,
      "headline": "Narrow loudness range — mix lacks dynamic contrast for trance",
      "summary": "Loudness range of 2.66 LU is very narrow for trance, which benefits from 4–6 LU of contrast between buildups, drops, and breakdowns. The flat dynamics prevent the drop from hitting hard — everything sits at roughly the same loudness throughout.",
      "body": "Loudness range of 2.66 LU is very narrow for trance, which benefits from 4–6 LU of contrast between buildups, drops, and breakdowns. The flat dynamics prevent the drop from hitting hard — everything sits at roughly the same loudness throughout.",
      "metricLine": "Loudness range (LU)",
      "whyItMatters": "Trance lives on the contrast between quiet breakdowns and explosive drops. Without dynamic range, the drop feels weak even if it's technically loud. Listeners need that 'lift' when the kick comes…",
      "presetName": null,
      "evidence": [
        {
          "label": "Loudness range (LU)",
          "stems": null,
          "value": 2.6648231675182252,
          "metric": "phase1.loudness_range_lu",
          "delta_pct": null,
          "expected_range": [
            4,
            6
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Integrated LUFS",
          "stems": null,
          "value": -12.999443616023667,
          "metric": "phase1.lufs",
          "delta_pct": null,
          "expected_range": [
            -14,
            -12
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": {
        "target": {
          "name": "Master Bus",
          "type": "master"
        },
        "dsp_chain": [
          {
            "type": "gain",
            "params": {
              "gain_db": -2
            }
          },
          {
            "type": "compressor",
            "params": {
              "ratio": 2,
              "knee_db": 6,
              "attack_ms": 50,
              "release_ms": 200,
              "threshold_db": -8,
              "makeup_gain_db": 0
            }
          }
        ],
        "expected_outcome": "Loudness range will expand to 4–6 LU, allowing drops to hit 4–6 dB louder than breakdowns and buildups to crescendo naturally into the drop.",
        "ableton_hint": {
          "band": null,
          "device": "Glue Compressor",
          "preset_name": "Gentle bus glue 2:1 50ms"
        }
      },
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 30,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 0.7,
      "scope": "single_section",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-09",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "win",
      "category": "mono_compatibility",
      "confidence": 0.95,
      "priorityScore": 28,
      "impact": "med",
      "chartType": null,
      "headline": "Excellent mono compatibility — mix survives mono playback",
      "summary": "Mono compatibility at 93.6% is excellent. The mix collapses cleanly to mono with no phase cancellation. Stereo correlation at 0.75 (positive) ensures no elements disappear on club subs or phone speakers.",
      "body": "Mono compatibility at 93.6% is excellent. The mix collapses cleanly to mono with no phase cancellation. Stereo correlation at 0.75 (positive) ensures no elements disappear on club subs or phone speakers.",
      "metricLine": "Mono compatibility (93.6% = excellent)",
      "whyItMatters": "Club systems often sum bass to mono. Phone and tablet speakers are mono. This mix will sound consistent across all playback systems with no surprises or cancellation.",
      "presetName": null,
      "evidence": [
        {
          "label": "Mono compatibility (93.6% = excellent)",
          "stems": null,
          "value": 0.9362839408871892,
          "metric": "phase1.mono_compatibility",
          "delta_pct": null,
          "expected_range": [
            0.7,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Phase correlation (0.75 = phase-safe)",
          "stems": null,
          "value": 0.7532607037568414,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0,
            1
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Surround mono score (87.7% = good)",
          "stems": null,
          "value": 87.66296148857793,
          "metric": "phase9.surround.mono_compatibility",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1.4,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  },
  {
    "verdict": {
      "id": "sample-10",
      "analysisId": "sample",
      "specialist": "stereo_phase",
      "promptVersion": "stereo_phase@1.0.0",
      "model": "claude-sonnet-4-5",
      "severity": "win",
      "category": "stereo_phase",
      "confidence": 0.9,
      "priorityScore": 20,
      "impact": "med",
      "chartType": null,
      "headline": "Good phase coherence — no phase cancellation detected",
      "summary": "Phase coherence at 87.7% is very good. Positive stereo correlation (0.75) confirms no out-of-phase content. Left and right channels are properly aligned with no polarity issues.",
      "body": "Phase coherence at 87.7% is very good. Positive stereo correlation (0.75) confirms no out-of-phase content. Left and right channels are properly aligned with no polarity issues.",
      "metricLine": "Phase coherence (87.7% = very good)",
      "whyItMatters": "Phase-coherent mixes survive mono playback without element disappearance. This mix has clean L/R relationships with no polarity errors or destructive interference.",
      "presetName": null,
      "evidence": [
        {
          "label": "Phase coherence (87.7% = very good)",
          "stems": null,
          "value": 87.66303518784207,
          "metric": "phase9.surround.phase_score",
          "delta_pct": null,
          "expected_range": [
            70,
            100
          ],
          "frequency_range_hz": null
        },
        {
          "label": "Correlation (0.75 = positive, phase-safe)",
          "stems": null,
          "value": 0.7532607037568414,
          "metric": "phase1.stereo_correlation",
          "delta_pct": null,
          "expected_range": [
            0,
            1
          ],
          "frequency_range_hz": null
        }
      ],
      "fix": null,
      "sources": null,
      "problemId": null,
      "kind": "fault",
      "source": "llm_identifier",
      "dataTier": "audio_only",
      "fixable": true,
      "suspected": false,
      "where": null,
      "refines": null,
      "priorityBase": 20,
      "priorityCategoryWeight": 1,
      "priorityScopeMultiplier": 1,
      "scope": "full_track",
      "createdAt": "2026-09-21T00:00:00Z",
      "userState": {
        "dismissed": false,
        "applied": false,
        "feedback": null
      }
    },
    "corroboratedBy": []
  }
];
