"""Layer-2 schema contract: resolve consumer field paths against the
authoritative ``final_json`` path manifest, and compute current drift.

Pure (no DB, no LLM). The manifest (``schemas/final_json.contract.json``) is
generated by ``app.tools.build_schema_contract`` from real samples; this module
only reads it and answers "does this consumer path actually exist in what the
pipeline emits?".

Consumers checked by :func:`current_drift_offenders`:
  - **rules** — read paths extracted from ``rule_engine._RULES`` via the
    inspector's AST extractor.
  - **prompts** — dotted paths cited in ``prompts/experts/*.md`` (+ Triage).
  - **fixtures** — every leaf in ``tests/verdict_pipeline/fixtures/analyses/*.json``.

See ``PRPs/schema-contract-prevention-design.md`` for the why.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_WORKER_ROOT = Path(__file__).resolve().parents[2]          # components/worker
_REPO_ROOT = Path(__file__).resolve().parents[4]            # repo root
_CONTRACT_PATH = _REPO_ROOT / "schemas" / "final_json.contract.json"
_FIXTURES_DIR = _WORKER_ROOT / "tests" / "verdict_pipeline" / "fixtures" / "analyses"

_ARR_RE = re.compile(r"\[\d+\]")
# Dotted paths a consumer might cite. Anchored on the namespaces consumers
# actually use (production phaseN.* + the three legacy v1 namespaces the prompts
# still reference) so version tokens / prose never register as paths.
_PROMPT_PATH_RE = re.compile(
    r"\b(?:phase[1-9]|audio_analysis|section_analysis|stem_analysis)"
    r"(?:\.\w+(?:\[\d+\])?)+"
)


def _normalize(path: str) -> str:
    return _ARR_RE.sub("[]", path.strip())


def load_contract(path: Path = _CONTRACT_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def path_resolves(path: str, contract: dict[str, Any]) -> bool:
    """True if ``path`` is emitted by the pipeline per the contract.

    Resolves when the (array-normalized) path is: a runtime-injected bare key,
    an exact leaf, an *ancestor* of a leaf (reading a whole container), or under
    a dynamic-keyed container whose runtime keys we can't enumerate.
    """
    n = _normalize(path)
    if not n:
        return False
    if n in contract.get("bare_top_level_allowed", []):
        return True
    leaves: list[str] = contract["leaf_paths"]
    if n in leaves:
        return True
    if any(lf.startswith(n + ".") or lf.startswith(n + "[") for lf in leaves):
        return True
    for dp in contract.get("dynamic_prefixes", []):
        if n == dp or n.startswith(dp + ".") or n.startswith(dp + "["):
            return True
    return False


def prompt_paths(md_text: str) -> set[str]:
    """Dotted field paths a prompt directs the model to read."""
    return set(_PROMPT_PATH_RE.findall(md_text))


def fixture_paths(obj: Any, prefix: str = "") -> set[str]:
    """Every dotted leaf path present in a fixture analysis dict.

    Fixtures are already in flattened ``phaseN.*`` shape; if a raw ``phases``
    list is present we flatten first so the path style matches the contract.
    """
    if prefix == "" and isinstance(obj, dict) and "phases" in obj:
        from app.verdict_lib.flatten_analysis import flatten  # noqa: PLC0415
        obj = flatten(obj)
    out: set[str] = set()
    if isinstance(obj, dict):
        if not obj:
            out.add(prefix)
        for k, v in obj.items():
            out |= fixture_paths(v, f"{prefix}.{k}" if prefix else k)
    elif isinstance(obj, list):
        for it in obj:
            out |= fixture_paths(it, prefix + "[]")
    else:
        out.add(prefix)
    return out


# ── drift computation (shared by the CLI baseline writer + the lint test) ────


def _rule_offenders(contract: dict[str, Any]) -> list[str]:
    from app.tools.inspector.rule_introspect import read_paths_for_rule  # noqa: PLC0415
    from app.verdict_lib import rule_engine  # noqa: PLC0415

    out: list[str] = []
    for fn in rule_engine._RULES:
        for p in sorted(read_paths_for_rule(fn)):
            if not path_resolves(p, contract):
                out.append(f"{fn.__name__}::{p}")
    return out


def _prompt_files() -> list[Path]:
    from app.verdict_lib.prompt_loader import (  # noqa: PLC0415
        PROMPTS_DIR, SLUG_TO_FILENAME, TRIAGE_FILENAME,
    )
    names = sorted(set(SLUG_TO_FILENAME.values()) | {TRIAGE_FILENAME})
    return [PROMPTS_DIR / f"{n}.md" for n in names if (PROMPTS_DIR / f"{n}.md").exists()]


def _prompt_offenders(contract: dict[str, Any]) -> list[str]:
    out: list[str] = []
    for path in _prompt_files():
        text = path.read_text(encoding="utf-8")
        for p in sorted(prompt_paths(text)):
            if not path_resolves(p, contract):
                out.append(f"{path.name}::{p}")
    return out


def _fixture_offenders(contract: dict[str, Any]) -> list[str]:
    out: list[str] = []
    for path in sorted(_FIXTURES_DIR.glob("*.json")):
        obj = json.loads(path.read_text(encoding="utf-8"))
        for p in sorted(fixture_paths(obj)):
            if not path_resolves(p, contract):
                out.append(f"{path.name}::{p}")
    return out


def current_drift_offenders(contract: dict[str, Any] | None = None) -> dict[str, list[str]]:
    """Every consumer path that does NOT resolve, grouped by consumer kind.

    Fails closed: callers assert each scanned set is non-empty so a vacuous
    scan (moved files) can't masquerade as 'no drift'.
    """
    c = contract or load_contract()
    return {
        "rules": sorted(_rule_offenders(c)),
        "prompts": sorted(_prompt_offenders(c)),
        "fixtures": sorted(_fixture_offenders(c)),
    }


_KINDS = ("rules", "prompts", "fixtures")


def diff_new(current: dict[str, list[str]], baseline: dict[str, list[str]]) -> dict[str, list[str]]:
    """Offenders present now but NOT baselined — new drift (must be zero)."""
    return {k: sorted(set(current.get(k, [])) - set(baseline.get(k, []))) for k in _KINDS}


def diff_stale(current: dict[str, list[str]], baseline: dict[str, list[str]]) -> dict[str, list[str]]:
    """Baselined offenders that no longer occur — fixed; their baseline line
    must be deleted (the ratchet that forces the baseline to shrink)."""
    return {k: sorted(set(baseline.get(k, [])) - set(current.get(k, []))) for k in _KINDS}


def scan_sizes() -> dict[str, int]:
    """Counts of what was scanned (for fail-closed assertions)."""
    from app.verdict_lib import rule_engine  # noqa: PLC0415
    return {
        "rules": len(rule_engine._RULES),
        "prompts": len(_prompt_files()),
        "fixtures": len(list(_FIXTURES_DIR.glob("*.json"))),
    }
